import { NextRequest, NextResponse } from "next/server";
import { cookies } from "next/headers";
import { getLocaleFromCookies } from "@/lib/locale";
import { buildReportModel, type UpstreamReportData } from "@/lib/report/build-report-model";
import { buildCalculationSheetModel, type CalculationSheetModel } from "@/lib/report/calculation-sheet-model";
import { launchPdfBrowser, type PdfBrowser } from "@/lib/report/pdf-browser";
import { validateReportModel } from "@/lib/report/validate-report-model";
import { reportUrlForExport, resolveExportShareToken } from "../../export-share";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function safeFilename(value: string): string {
  return (value || "pilar-beregning")
    .replace(/[^a-zA-Z0-9æøåÆØÅ._-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 120);
}

function escapeHtml(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const LABELS = {
  nb: {
    kicker: "PILAR · BEREGNINGSARK",
    titleFallback: "Beregning",
    documentId: "Dokument-ID",
    date: "Dato",
    status: "Status",
    given: "Gitte data",
    assumptions: "Forutsetninger",
    calculation: "Stegvis beregning",
    results: "Resultater",
    notes: "Merknader",
    generatedNote:
      "Generert av PILAR. Beregningen skal kontrolleres av ansvarlig fagperson før bruk.",
  },
  nn: {
    kicker: "PILAR · BEREKNINGSARK",
    titleFallback: "Berekning",
    documentId: "Dokument-ID",
    date: "Dato",
    status: "Status",
    given: "Gjevne data",
    assumptions: "Føresetnader",
    calculation: "Stegvis berekning",
    results: "Resultat",
    notes: "Merknader",
    generatedNote:
      "Generert av PILAR. Berekninga skal kontrollerast av ansvarleg fagperson før bruk.",
  },
  en: {
    kicker: "PILAR · CALCULATION SHEET",
    titleFallback: "Calculation",
    documentId: "Document ID",
    date: "Date",
    status: "Status",
    given: "Given data",
    assumptions: "Assumptions",
    calculation: "Step-by-step calculation",
    results: "Results",
    notes: "Notes",
    generatedNote:
      "Generated by PILAR. The calculation must be checked by a qualified professional before use.",
  },
} as const;

function renderCalculationSheetHtml(sheet: CalculationSheetModel): string {
  const displayLanguage = sheet.meta.displayLanguage ?? sheet.meta.locale;
  const labels = LABELS[displayLanguage] ?? LABELS.nb;
  const title = sheet.meta.title || labels.titleFallback;
  const row = (label: string, value: string) => `
    <div class="meta-card">
      <span>${escapeHtml(label)}</span>
      <strong>${escapeHtml(value || "-")}</strong>
    </div>`;
  const section = (index: string, heading: string, body: string, modifier = "") => body.trim()
    ? `<section class="section ${escapeHtml(modifier)}">
        <div class="section-head">
          <span>${escapeHtml(index)}</span>
          <h2>${escapeHtml(heading)}</h2>
        </div>
        ${body}
      </section>`
    : "";

  const given = sheet.given
    .map((item) => `
      <div class="data-row">
        <strong>${escapeHtml(item.label)}</strong>
        <span>${escapeHtml(item.unit ? `${item.value} ${item.unit}` : item.value)}</span>
      </div>`)
    .join("");
  const assumptions = sheet.assumptions
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");
  const steps = sheet.steps
    .map((step) => `
      <article class="step">
        <div class="step-head">
          <span>${escapeHtml(String(step.number).padStart(2, "0"))}</span>
          <h3>${escapeHtml(step.title)}</h3>
        </div>
        ${step.explanation ? `<p>${escapeHtml(step.explanation)}</p>` : ""}
        ${step.formulas
          .map((formula) => `<pre>${escapeHtml(formula.plain || formula.latex)}</pre>`)
          .join("")}
      </article>`)
    .join("");
  const results = sheet.results
    .map((item) => `
      <div class="data-row">
        <strong>${escapeHtml(item.label)}</strong>
        <span>${escapeHtml(item.unit ? `${item.value} ${item.unit}` : item.value)}</span>
      </div>`)
    .join("");
  const notes = sheet.notes
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");

  return `<!doctype html>
<html lang="${escapeHtml(displayLanguage)}">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    @page { size: A4; margin: 16mm 14mm 17mm; }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      color: #171717;
      background: #fff;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      font-size: 10pt;
      line-height: 1.44;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    .sheet { width: 100%; }
    .cover {
      padding-bottom: 8mm;
      margin-bottom: 7mm;
      border-bottom: 0.8pt solid #d8d3c8;
      break-after: avoid;
    }
    .kicker {
      color: #8a5d00;
      font-size: 7.8pt;
      font-weight: 700;
      letter-spacing: .1em;
      text-transform: uppercase;
      font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
    }
    h1 {
      margin: 2.5mm 0 1.8mm;
      font-family: Georgia, "Times New Roman", serif;
      font-size: 24pt;
      font-weight: 650;
      line-height: 1.08;
      letter-spacing: -0.01em;
    }
    .subtitle { margin: 0; color: #4f4a42; font-size: 10.4pt; }
    .meta { display: grid; grid-template-columns: repeat(3, 1fr); gap: 2.5mm; margin: 7mm 0 0; }
    .meta-card, .data-row {
      border: 0.8pt solid #d8d3c8;
      border-left: 2.4pt solid #1f1d18;
      padding: 2.6mm 3mm;
      break-inside: avoid;
      background: #faf8f2;
    }
    .meta-card span {
      display: block;
      color: #6d665b;
      font-size: 7.4pt;
      font-weight: 700;
      letter-spacing: .08em;
      text-transform: uppercase;
      margin-bottom: 1.2mm;
    }
    .meta-card strong { font-size: 10pt; }
    .review-note {
      margin: 0 0 7mm;
      padding: 3.2mm 4mm;
      border: 0.8pt solid #d4a017;
      border-left: 3pt solid #b9821a;
      background: #fff7e1;
      color: #1f1d18;
      break-inside: avoid;
    }
    .section { margin: 7mm 0; break-inside: auto; }
    .section-head {
      display: flex;
      align-items: baseline;
      gap: 3mm;
      margin: 0 0 3mm;
      padding-bottom: 1.8mm;
      border-bottom: 0.7pt solid #d8d3c8;
      break-after: avoid;
    }
    .section-head span {
      color: #b9821a;
      font-size: 8pt;
      font-weight: 700;
      font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
    }
    h2 { margin: 0; font-size: 14.5pt; line-height: 1.15; }
    h3 { margin: 0; font-size: 11.3pt; line-height: 1.2; }
    .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 2.4mm; }
    .data-row {
      display: grid;
      grid-template-columns: minmax(0, 1fr) auto;
      align-items: baseline;
      gap: 4mm;
    }
    .data-row strong { min-width: 0; overflow-wrap: anywhere; }
    .data-row span { font-weight: 650; white-space: nowrap; }
    .step {
      margin: 0 0 4.2mm;
      padding-bottom: 3.8mm;
      border-bottom: 0.7pt solid #e7e1d6;
      break-inside: auto;
    }
    .step-head {
      display: flex;
      align-items: baseline;
      gap: 2.4mm;
      margin-bottom: 1.6mm;
      break-after: avoid;
    }
    .step-head span {
      color: #b9821a;
      font-size: 7.6pt;
      font-weight: 700;
      letter-spacing: .08em;
      font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
      white-space: nowrap;
    }
    .step p { margin: 0 0 2.2mm; color: #2f2b26; }
    pre {
      margin: 2mm 0 0;
      padding: 2.4mm 3mm;
      border-left: 2pt solid #d8d3c8;
      background: #f5f3ee;
      white-space: pre-wrap;
      font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
      font-size: 8.2pt;
      line-height: 1.36;
      overflow-wrap: anywhere;
      break-inside: avoid;
    }
    ul { margin: 0; padding-left: 18px; }
    li { margin: 2mm 0; }
    footer {
      margin-top: 8mm;
      padding-top: 3mm;
      border-top: 0.8pt solid #d8d3c8;
      color: #666;
      font-size: 8.6pt;
    }
  </style>
</head>
<body>
  <main class="sheet" data-calculation-sheet-ready="true">
    <header class="cover">
      <div class="kicker">${escapeHtml(labels.kicker)}</div>
      <h1>${escapeHtml(title)}</h1>
      ${sheet.meta.subtitle ? `<p class="subtitle">${escapeHtml(sheet.meta.subtitle)}</p>` : ""}
      <div class="meta">
        ${row(labels.documentId, sheet.meta.documentId)}
        ${row(labels.date, sheet.meta.date)}
        ${row(labels.status, sheet.meta.status)}
      </div>
    </header>
    <p class="review-note">${escapeHtml(labels.generatedNote)}</p>
    ${section("01", labels.given, given ? `<div class="grid">${given}</div>` : "", "section--given")}
    ${section("02", labels.assumptions, assumptions ? `<ul>${assumptions}</ul>` : "", "section--assumptions")}
    ${section("03", labels.calculation, steps, "section--calculation")}
    ${section("04", labels.results, results ? `<div class="grid">${results}</div>` : "", "section--results")}
    ${section("05", labels.notes, notes ? `<ul>${notes}</ul>` : "", "section--notes")}
    <footer>${escapeHtml(labels.generatedNote)}</footer>
  </main>
</body>
</html>`;
}

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ run_id: string }> },
) {
  let stage = "init";
  let browser: PdfBrowser | null = null;

  try {
    stage = "params";
    const { run_id } = await context.params;
    if (!run_id) {
      return NextResponse.json({ error: "run_id is required" }, { status: 400 });
    }

    stage = "locale";
    const locale = getLocaleFromCookies(await cookies());
    const origin = request.nextUrl.origin;
    const cookieHeader = request.headers.get("cookie") ?? "";
    const share = await resolveExportShareToken({ request, runId: run_id, cookieHeader });

    stage = "fetch_agent_e";
    const agentERes = share.token && share.source === "query"
      ? await fetch(`${origin}/api/runs/${run_id}?share=${encodeURIComponent(share.token)}`, {
          headers: {
            ...(cookieHeader ? { Cookie: cookieHeader } : {}),
          },
        })
      : await fetch(`${origin}/api/agent-e`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            ...(cookieHeader ? { Cookie: cookieHeader } : {}),
          },
          body: JSON.stringify({ run_id, locale }),
        });

    if (!agentERes.ok) {
      return NextResponse.json(
        { error: "Kunne ikke hente rapport-data" },
        { status: agentERes.status },
      );
    }

    stage = "parse_agent_e";
    const upstream: UpstreamReportData = await agentERes.json();

    stage = "build_models";
    const reportUrl = reportUrlForExport(origin, run_id, share.token);
    const reportModel = buildReportModel(upstream, {
      locale,
      reportUrl,
      audience: "student",
    });

    const validation = validateReportModel(reportModel);
    if (!validation.ok || validation.warnings.length > 0) {
      console.warn("Calculation PDF export: report model validation", {
        run_id,
        ok: validation.ok,
        errors: validation.errors,
        warnings: validation.warnings,
      });
    }

    const sheet = buildCalculationSheetModel(reportModel);
    const html = renderCalculationSheetHtml(sheet);

    stage = "launch_puppeteer";
    browser = await launchPdfBrowser();

    stage = "open_page";
    const page = await browser.newPage();
    await page.setViewport({ width: 794, height: 1123, deviceScaleFactor: 1 });

    stage = "render_sheet_html";
    await page.setContent(html, {
      waitUntil: "networkidle0",
      timeout: 30_000,
    });

    stage = "wait_for_sheet";
    await page.waitForSelector('[data-calculation-sheet-ready="true"]', {
      timeout: 90_000,
    });

    stage = "render_pdf";
    await page.emulateMediaType("print");
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      preferCSSPageSize: true,
      margin: {
        top: "18mm",
        right: "16mm",
        bottom: "18mm",
        left: "16mm",
      },
    });

    const filename = safeFilename(`PILAR-${run_id.slice(0, 8)}-beregning`);
    return new NextResponse(new Uint8Array(pdf), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error: unknown) {
    const errorName = error instanceof Error ? error.name : typeof error;
    const messageLength = error instanceof Error ? error.message.length : String(error).length;
    console.error("Calculation PDF export error:", {
      stage,
      error_name: errorName,
      message_length: messageLength,
    });
    return NextResponse.json({ error: "Ukjent feil" }, { status: 500 });
  } finally {
    if (browser) {
      await browser.close().catch(() => undefined);
    }
  }
}
