import { NextRequest, NextResponse } from "next/server";
import { cookies } from "next/headers";
import { getLocaleFromCookies } from "@/lib/locale";
import { buildReportModel, type UpstreamReportData } from "@/lib/report/build-report-model";
import { buildCalculationSheetModel, type CalculationSheetModel } from "@/lib/report/calculation-sheet-model";
import { validateReportModel } from "@/lib/report/validate-report-model";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type PuppeteerModule = {
  default?: {
    launch: (options: Record<string, unknown>) => Promise<PuppeteerBrowser>;
  };
  launch?: (options: Record<string, unknown>) => Promise<PuppeteerBrowser>;
};

type PuppeteerBrowser = {
  newPage: () => Promise<PuppeteerPage>;
  close: () => Promise<void>;
};

type PuppeteerPage = {
  setExtraHTTPHeaders: (headers: Record<string, string>) => Promise<void>;
  setViewport: (viewport: { width: number; height: number; deviceScaleFactor?: number }) => Promise<void>;
  goto: (url: string, options?: Record<string, unknown>) => Promise<unknown>;
  setContent: (html: string, options?: Record<string, unknown>) => Promise<void>;
  waitForSelector: (selector: string, options?: Record<string, unknown>) => Promise<unknown>;
  emulateMediaType: (type: "screen" | "print") => Promise<void>;
  pdf: (options: Record<string, unknown>) => Promise<Buffer>;
};

function safeFilename(value: string): string {
  return (value || "pilar-beregning")
    .replace(/[^a-zA-Z0-9æøåÆØÅ._-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 120);
}

function escapeHtml(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const LABELS = {
  nb: {
    kicker: "PILAR · BEREGNINGSARK",
    titleFallback: "Beregning",
    documentId: "Dokument-ID",
    date: "Dato",
    status: "Status",
    given: "Gitte data",
    assumptions: "Forutsetninger",
    calculation: "Stegvis beregning",
    results: "Resultater",
    notes: "Merknader",
    generatedNote:
      "Generert av PILAR. Beregningen skal kontrolleres av ansvarlig fagperson før bruk.",
  },
  nn: {
    kicker: "PILAR · BEREKNINGSARK",
    titleFallback: "Berekning",
    documentId: "Dokument-ID",
    date: "Dato",
    status: "Status",
    given: "Gjevne data",
    assumptions: "Føresetnader",
    calculation: "Stegvis berekning",
    results: "Resultat",
    notes: "Merknader",
    generatedNote:
      "Generert av PILAR. Berekninga skal kontrollerast av ansvarleg fagperson før bruk.",
  },
  en: {
    kicker: "PILAR · CALCULATION SHEET",
    titleFallback: "Calculation",
    documentId: "Document ID",
    date: "Date",
    status: "Status",
    given: "Given data",
    assumptions: "Assumptions",
    calculation: "Step-by-step calculation",
    results: "Results",
    notes: "Notes",
    generatedNote:
      "Generated by PILAR. The calculation must be checked by a qualified professional before use.",
  },
} as const;

function renderCalculationSheetHtml(sheet: CalculationSheetModel): string {
  const displayLanguage = sheet.meta.displayLanguage ?? sheet.meta.locale;
  const labels = LABELS[displayLanguage] ?? LABELS.nb;
  const title = sheet.meta.title || labels.titleFallback;
  const row = (label: string, value: string) => `
    <div class="meta-card">
      <span>${escapeHtml(label)}</span>
      <strong>${escapeHtml(value || "-")}</strong>
    </div>`;
  const section = (heading: string, body: string) => body.trim()
    ? `<section><h2>${escapeHtml(heading)}</h2>${body}</section>`
    : "";

  const given = sheet.given
    .map((item) => `
      <div class="data-row">
        <strong>${escapeHtml(item.label)}</strong>
        <span>${escapeHtml(item.unit ? `${item.value} ${item.unit}` : item.value)}</span>
      </div>`)
    .join("");
  const assumptions = sheet.assumptions
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");
  const steps = sheet.steps
    .map((step) => `
      <article class="step">
        <h3>${step.number}. ${escapeHtml(step.title)}</h3>
        ${step.explanation ? `<p>${escapeHtml(step.explanation)}</p>` : ""}
        ${step.formulas
          .map((formula) => `<pre>${escapeHtml(formula.plain || formula.latex)}</pre>`)
          .join("")}
      </article>`)
    .join("");
  const results = sheet.results
    .map((item) => `
      <div class="data-row">
        <strong>${escapeHtml(item.label)}</strong>
        <span>${escapeHtml(item.unit ? `${item.value} ${item.unit}` : item.value)}</span>
      </div>`)
    .join("");
  const notes = [...sheet.notes, labels.generatedNote]
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("");

  return `<!doctype html>
<html lang="${escapeHtml(displayLanguage)}">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    @page { size: A4; margin: 18mm 16mm; }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      color: #172033;
      background: #fff;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      font-size: 11pt;
      line-height: 1.5;
    }
    .sheet { width: 100%; }
    .kicker { color: #617089; font-size: 8.5pt; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
    h1 { margin: 8px 0 6px; font-size: 24pt; line-height: 1.12; }
    .subtitle { margin: 0 0 18px; color: #4c5a70; }
    .meta { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin: 18px 0 24px; }
    .meta-card, .data-row {
      border: 1px solid #d8dee8;
      border-radius: 6px;
      padding: 8px 10px;
      break-inside: avoid;
    }
    .meta-card span { display: block; color: #617089; font-size: 8.5pt; text-transform: uppercase; }
    section { margin: 22px 0; break-inside: auto; }
    h2 { margin: 0 0 10px; font-size: 15pt; }
    h3 { margin: 0 0 6px; font-size: 12pt; }
    .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; }
    .data-row { display: flex; justify-content: space-between; gap: 12px; }
    .step { margin: 0 0 14px; padding-bottom: 12px; border-bottom: 1px solid #e5e9f0; break-inside: avoid; }
    pre {
      margin: 8px 0 0;
      padding: 8px 10px;
      border-radius: 6px;
      background: #f6f8fb;
      white-space: pre-wrap;
      font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
      font-size: 9.5pt;
    }
    ul { margin: 0; padding-left: 18px; }
    li { margin: 4px 0; }
  </style>
</head>
<body>
  <main class="sheet" data-calculation-sheet-ready="true">
    <div class="kicker">${escapeHtml(labels.kicker)}</div>
    <h1>${escapeHtml(title)}</h1>
    ${sheet.meta.subtitle ? `<p class="subtitle">${escapeHtml(sheet.meta.subtitle)}</p>` : ""}
    <div class="meta">
      ${row(labels.documentId, sheet.meta.documentId)}
      ${row(labels.date, sheet.meta.date)}
      ${row(labels.status, sheet.meta.status)}
    </div>
    ${section(labels.given, given ? `<div class="grid">${given}</div>` : "")}
    ${section(labels.assumptions, assumptions ? `<ul>${assumptions}</ul>` : "")}
    ${section(labels.calculation, steps)}
    ${section(labels.results, results ? `<div class="grid">${results}</div>` : "")}
    ${section(labels.notes, notes ? `<ul>${notes}</ul>` : "")}
  </main>
</body>
</html>`;
}

async function loadPuppeteer(): Promise<PuppeteerModule> {
  try {
    // Bruk variabel import slik at prosjektet framleis kan typechecke før
    // puppeteer er installert. Runtime gir ei tydeleg feilmelding om pakken manglar.
    const moduleName = "puppeteer";
    return (await import(moduleName)) as PuppeteerModule;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(
      `PDF-motoren manglar. Installer puppeteer først: npm install puppeteer. Detalj: ${message}`,
    );
  }
}

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ run_id: string }> },
) {
  let stage = "init";
  let browser: PuppeteerBrowser | null = null;

  try {
    stage = "params";
    const { run_id } = await context.params;
    if (!run_id) {
      return NextResponse.json({ error: "run_id is required" }, { status: 400 });
    }

    stage = "locale";
    const locale = getLocaleFromCookies(await cookies());
    const origin = request.nextUrl.origin;
    const cookieHeader = request.headers.get("cookie") ?? "";

    stage = "fetch_agent_e";
    const agentERes = await fetch(`${origin}/api/agent-e`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(cookieHeader ? { Cookie: cookieHeader } : {}),
      },
      body: JSON.stringify({ run_id, locale }),
    });

    if (!agentERes.ok) {
      return NextResponse.json(
        { error: "Kunne ikke hente rapport-data" },
        { status: agentERes.status },
      );
    }

    stage = "parse_agent_e";
    const upstream: UpstreamReportData = await agentERes.json();

    stage = "build_models";
    const reportUrl = `${origin}/rapport/${run_id}`;
    const reportModel = buildReportModel(upstream, {
      locale,
      reportUrl,
      audience: "student",
    });

    const validation = validateReportModel(reportModel);
    if (!validation.ok || validation.warnings.length > 0) {
      console.warn("Calculation PDF export: report model validation", {
        run_id,
        ok: validation.ok,
        errors: validation.errors,
        warnings: validation.warnings,
      });
    }

    const sheet = buildCalculationSheetModel(reportModel);
    const html = renderCalculationSheetHtml(sheet);

    stage = "launch_puppeteer";
    const puppeteerModule = await loadPuppeteer();
    const launcher = puppeteerModule.default?.launch ?? puppeteerModule.launch;
    if (!launcher) {
      throw new Error("Kunne ikkje starte puppeteer: launch() manglar.");
    }

    browser = await launcher({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--font-render-hinting=medium",
      ],
    });

    stage = "open_page";
    const page = await browser.newPage();
    await page.setViewport({ width: 794, height: 1123, deviceScaleFactor: 1 });

    stage = "render_sheet_html";
    await page.setContent(html, {
      waitUntil: "networkidle0",
      timeout: 30_000,
    });

    stage = "wait_for_sheet";
    await page.waitForSelector('[data-calculation-sheet-ready="true"]', {
      timeout: 90_000,
    });

    stage = "render_pdf";
    await page.emulateMediaType("print");
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      preferCSSPageSize: true,
      margin: {
        top: "18mm",
        right: "16mm",
        bottom: "18mm",
        left: "16mm",
      },
    });

    const filename = safeFilename(`PILAR-${run_id.slice(0, 8)}-beregning`);
    return new NextResponse(new Uint8Array(pdf), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error: unknown) {
    const errorName = error instanceof Error ? error.name : typeof error;
    const messageLength = error instanceof Error ? error.message.length : String(error).length;
    console.error("Calculation PDF export error:", {
      stage,
      error_name: errorName,
      message_length: messageLength,
    });
    return NextResponse.json({ error: "Ukjent feil" }, { status: 500 });
  } finally {
    if (browser) {
      await browser.close().catch(() => undefined);
    }
  }
}
