import { inferCalculationEnglishDisplay } from "@/lib/international/display";

function calculationSheetDisplayLanguage(sheet: CalculationSheetModel): PilarDisplayLanguage {
  const explicit = sheet.meta.displayLanguage;
  if (explicit === "en" || explicit === "nb" || explicit === "nn") return explicit;
  const signal = [sheet.meta.title, sheet.meta.subtitle, ...sheet.assumptions, ...sheet.notes].join("\n");
  return inferCalculationEnglishDisplay(signal) ? "en" : sheet.meta.locale;
}

function labelFor(language: PilarDisplayLanguage, key: "given" | "assumptions" | "calculation" | "results" | "notes" | "step"): string {
  const en = { given: "Given data", assumptions: "Assumptions", calculation: "Step-by-step calculation", results: "Results", notes: "Notes", step: "Step" };
  const nb = { given: "Gitte data", assumptions: "Forutsetninger", calculation: "Stegvis beregning", results: "Resultater", notes: "Merknader", step: "Steg" };
  const nn = { given: "Gjevne data", assumptions: "Føresetnader", calculation: "Stegvis berekning", results: "Resultat", notes: "Merknader", step: "Steg" };
  return language === "en" ? en[key] : language === "nn" ? nn[key] : nb[key];
}
import type { CalculationSheetModel } from "./calculation-sheet-model";
import type { PilarDisplayLanguage } from "@/lib/international/display";


function isEnglishDisplayLanguage(value: unknown): boolean {
  return value === "en";
}


export type CalculationLatexMode = "section" | "full-document";

export type RenderCalculationLatexOptions = {
  mode?: CalculationLatexMode;
};

function escapeLatexText(value: string): string {
  return String(value ?? "")
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/&/g, "\\&")
    .replace(/%/g, "\\%")
    .replace(/#/g, "\\#")
    .replace(/\$/g, "\\$")
    .replace(/_/g, "\\_")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    .trim();
}

function unitLatex(unit: string | null): string {
  if (!unit) return "";
  const escaped = escapeLatexText(unit)
    .replace(/²/g, "^2")
    .replace(/³/g, "^3")
    .replace(/mm2/g, "mm^2")
    .replace(/cm3/g, "cm^3")
    .replace(/m2/g, "m^2");
  return `\\,\\mathrm{${escaped}}`;
}

function valueLine(symbolLatex: string, value: string, unit: string | null): string {
  return `\\[\n${symbolLatex} = ${escapeLatexText(value)}${unitLatex(unit)}\n\\]`;
}

function proseToLatexParagraph(value: string): string {
  const text = escapeLatexText(value);
  if (!text) return "";
  return text
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.replace(/\n/g, " "))
    .filter(Boolean)
    .join("\n\n");
}

function displayMath(latex: string): string {
  const trimmed = latex.trim();
  if (!trimmed) return "";
  return `\\[\n${trimmed}\n\\]`;
}

function fullDocumentStart(title: string, displayLanguage: PilarDisplayLanguage): string[] {
  return [
    "\\documentclass[11pt,a4paper]{article}",
    "\\usepackage[utf8]{inputenc}",
    "\\usepackage[T1]{fontenc}",
    isEnglishDisplayLanguage(displayLanguage) ? "\\usepackage[english]{babel}" : "\\usepackage[norsk]{babel}",
    "\\usepackage{amsmath,amssymb}",
    "\\usepackage{siunitx}",
    "\\usepackage{geometry}",
    "\\geometry{margin=25mm}",
    "\\setlength{\\parindent}{0pt}",
    "\\setlength{\\parskip}{0.65em}",
    "",
    `\\title{${title}}`,
    isEnglishDisplayLanguage(displayLanguage) ? "\\author{Generated by PILAR}" : "\\author{Generert av PILAR}",
    "\\date{}",
    "",
    "\\begin{document}",
    "\\maketitle",
    "",
  ];
}

export function renderCalculationSheetLatex(
  sheet: CalculationSheetModel,
  options: RenderCalculationLatexOptions = {},
): string {
  const L = sheet.meta.locale;
  const D: PilarDisplayLanguage = (sheet.meta.displayLanguage ?? L) as PilarDisplayLanguage;
  const mode = options.mode ?? "section";
  const title = escapeLatexText(sheet.meta.title || "Beregning");
  const subtitle = escapeLatexText(sheet.meta.subtitle || "");
  const date = escapeLatexText(sheet.meta.date || "");
  const documentId = escapeLatexText(sheet.meta.documentId || "");

  const lines: string[] = [];
  if (isEnglishDisplayLanguage(D)) {
    lines.push("% Generated by PILAR");
    lines.push("% This file can be pasted directly into Overleaf or included with \\input{...}.");
    lines.push("% Manual verification by a qualified professional is required before use.");
  } else {
    lines.push("% Generert av PILAR");
    lines.push("% Denne fila kan limast direkte inn i Overleaf eller inkluderast med \\input{...}.");
    lines.push("% Hugs manuell kontroll av ansvarleg fagperson før bruk i prosjektering.");
  }
  lines.push("");

  if (mode === "full-document") {
    lines.push(...fullDocumentStart(title, D));
  } else {
    lines.push(`\\section{${title}}`);
  }

  if (subtitle) lines.push(`\\textit{${subtitle}}\\par`);
  lines.push("\\smallskip");
  lines.push(isEnglishDisplayLanguage(D)
    ? `\\noindent\\textbf{Document ID:} ${documentId}\\quad\\textbf{Date:} ${date}`
    : `\\noindent\\textbf{Dokument-ID:} ${documentId}\\quad\\textbf{Dato:} ${date}`);

  lines.push("");

  if (sheet.given.length > 0) {
    lines.push(`\\subsection{${isEnglishDisplayLanguage(D) ? "Given data" : isEnglishDisplayLanguage(D) ? "Given data" : L === "nn" ? "Gjevne data" : "Gitte data"}}`);
    for (const item of sheet.given) {
      lines.push(valueLine(item.latex, item.value, item.unit));
    }
    lines.push("");
  }

  if (sheet.assumptions.length > 0) {
    lines.push(`\\subsection{${isEnglishDisplayLanguage(D) ? "Assumptions" : isEnglishDisplayLanguage(D) ? "Assumptions" : L === "nn" ? "Føresetnader" : "Forutsetninger"}}`);
    lines.push("\\begin{itemize}");
    for (const assumption of sheet.assumptions) {
      lines.push(`  \\item ${escapeLatexText(assumption)}`);
    }
    lines.push("\\end{itemize}");
    lines.push("");
  }

  lines.push(`\\subsection{${isEnglishDisplayLanguage(D) ? "Step-by-step calculation" : isEnglishDisplayLanguage(D) ? "Step-by-step calculation" : L === "nn" ? "Stegvis berekning" : "Stegvis beregning"}}`);
  for (const step of sheet.steps) {
    lines.push(`\\subsubsection{${escapeLatexText(step.title)}}`);
    const explanation = proseToLatexParagraph(step.explanation);
    if (explanation) lines.push(explanation);
    for (const formula of step.formulas) {
      const math = displayMath(formula.latex);
      if (math) lines.push(math);
    }
    lines.push("");
  }

  if (sheet.results.length > 0) {
    lines.push(`\\subsection{${isEnglishDisplayLanguage(D) ? "Results" : isEnglishDisplayLanguage(D) ? "Results" : L === "nn" ? "Resultat" : "Resultater"}}`);
    for (const result of sheet.results) {
      lines.push(valueLine(result.latex, result.value, result.unit));
    }
    lines.push("");
  }

  if (sheet.notes.length > 0) {
    lines.push(`\\subsection{${isEnglishDisplayLanguage(D) ? "Notes" : "Merknader"}}`);
    lines.push("\\begin{itemize}");
    for (const note of sheet.notes) {
      lines.push(`  \\item ${escapeLatexText(note)}`);
    }
    lines.push("\\end{itemize}");
    lines.push("");
  }

  lines.push("\\smallskip");
  lines.push(isEnglishDisplayLanguage(D)
    ? "\\noindent\\textit{Generated by PILAR. The calculation must be checked by a qualified professional before use.}"
    : "\\noindent\\textit{Generated by PILAR. The calculation must be checked by a qualified professional before use.}");
  lines.push("");

  if (mode === "full-document") {
    lines.push("\\end{document}");
    lines.push("");
  }

  return lines.join("\n");
}
