import type { Locale } from "@/lib/locale";
import type { EngineeringContext } from "@/lib/engineering-context";

export type PilarDisplayLanguage = Locale | "en";



export const SPRINT336_ENGLISH_LABEL_BY_KEY: Record<string, string> = {
  // Generic/report navigation
  samandrag: "Summary",
  berekningTOC: "Calculation",
  vurdering: "Assessment",
  kontroll: "Review",
  ukjent: "Unknown",
  tilbake: "← Back",
  innhald: "Contents",
  metadata: "Metadata",
  metaID: "ID",
  metaDato: "Date",
  metaVersjon: "Version",
  berekningsnotat: "Calculation note",
  dokumentID: "Document ID:",
  forsideDato: "Date:",
  forsideStatus: "Status:",
  forsideRapportVersjon: "Report version:",
  viktigMerknad: "IMPORTANT NOTE",
  forespurselLabel: "REQUEST",
  bandDimensjonerande: "DEMAND / DESIGN VALUES",
  bandBruksgrense: "SERVICEABILITY",
  bandInputGeometri: "INPUT AND GEOMETRY",
  sub21Forutsetninger: "02.1 — ASSUMPTIONS",
  sub22Resultat: "02.2 — RESULTS",
  sub23Stegvis: "02.3 — STEP-BY-STEP CALCULATION",
  stegPrefix: "STEP",
  stegKontroll: "CHECK",
  chapter01Title: "Summary",
  chapter02Title: "Calculation",
  chapter03Title: "Assessment",
  chapter04Title: "Review",
  sub31FagleVurdering: "03.1 — ENGINEERING ASSESSMENT",
  sub32IkkjeBerekna: "03.2 — WHAT IS NOT CALCULATED",
  sub33Advarsler: "03.3 — WARNINGS",
  sub41Konstruktorkontroll: "04.1 — ENGINEER COMPARISON",
  sub42KontrollorAvgjerd: "04.2 — CONTROLLER DECISION",
  sub43Konklusjon: "04.3 — CONCLUSION",
  bandIkkjeDekka: "NOT COVERED BY THIS REPORT",
  advarselLabel: "WARNING",
  avgjerdLabel: "DECISION",
  signKontrollertCaption: "Name · title · company",
  signSignaturCaption: "Manual signature",
  signDatoCaption: "MM/DD/YYYY",
  marginaliaTitle: "GLOSSARY",
  kontrollSammeResultatKort: "Both engineers reached numerically identical values, shown in the table below.",
  kontrollMedAvvikKort: "The table below compares the independent results row by row. Differences are marked.",
  kontrollFallback: "They reached the same result.",
  verifikasjonKolStorleik: "Quantity",
  verifikasjonKolKonstruktorA: "Engineer A",
  verifikasjonKolKonstruktorB: "Engineer B",
  verifikasjonKolSamsvar: "Match",
  verifikasjonManglar: "—",
  verifikasjonAvvikKort: "Difference",
  verifikasjonSamsvarAria: "Match between the engineers",
  verifikasjonAvvikAria: "Difference between the engineers",
  verifikasjonUkjentAria: "Value unavailable from Engineer B",
  forsideMetaDokumentID: "Document ID",
  forsideMetaBrukar: "User",
  forsideMetaDato: "Date",
  forsideMetaStatus: "Status",
  forsideMetaVersjon: "Version",
  forsideFallbackTittel: "Calculation note",
  forsideTillitOverskrift: "Trust",
  forsideAITekst: "AI-generated document",
  qrAccessTitle: "Scan for web version",
  qrAccessText: "Opens the report online with control status, pipeline trace and shareable link for classmates or colleagues.",
  qrAccessUrlLabel: "Report link",
  qrAccessPipeline: "Web version + pipeline",
  coverKeyResults: "Key results",
  disclaimerKort: "The content is support, learning aid or preliminary technical assessment only. It does not replace review by a qualified professional.",
  disclaimer: "This document was generated by an AI-based calculation and documentation tool. The content is support, learning aid or preliminary technical assessment only. It does not replace review by a qualified professional, responsible engineer or approved organization. All calculations, assumptions, standard references, material data and conclusions must be verified before use in real projects.",
  samandragH2: "Summary",
  forespurnadH3: "Request",
  berekningH2: "Calculation",
  inputTolkingH3: "Input interpretation",
  statusPrefix: "Status:",
  foresetnaderH3: "Assumptions",
  resultatH3: "Results",
  stegvisUtrekningH3: "Step-by-step calculation",
  visProsaUtrekning: "Show prose calculation",
  vurderingH2: "Assessment",
  fagleVurderingH3: "Engineering assessment",
  kvaErIkkjeReknaH3: "What is not calculated",
  atvaringarH3: "Warnings",
  kontrollH2: "Review",
  konstruktorkontrollH3: "Engineer comparison",
  berekningaLoyst: "The calculation was solved independently by two AI engineers (Engineer A and Engineer B).",
  kontrollorAvgjerd: "Controller decision",
  konklusjonH3: "Conclusion",
  forebelsBerekning: "Preliminary calculation — must be checked by a qualified professional before use in design work.",
  kontrollertAv: "Reviewed by",
  signatur: "Signature",
  footerDato: "Date",
  generert: "Generated",
  handlingar: "Actions",
  lastNedPDF: "Download PDF",
  lastNedWord: "Download Word",
  lagNyBerekning: "Create new calculation from this →",
  saMissionControl: "See Mission Control →",
  sendTilbakemelding: "Send feedback",
  kontrollstatus: "Control status",
  statusInputTolking: "Input interpretation",
  statusKonstruktorA: "Engineer A",
  statusKonstruktorB: "Engineer B",
  statusSamanlikning: "Comparison",
  statusKontrollor: "Controller",
  statusFagperson: "Professional reviewer",
  ikkjeKontrollert: "Not reviewed",

  // Workbench/result view
  kontrollor: "Controller",
  kontrollorPopover1: "The Controller agent reads both engineers and the Comparator, then decides whether the result is safe enough to show. It does",
  kontrollorPopover2: "not",
  kontrollorPopover3: "replace professional review.",
  sluttkonklusjonUtelaten: "Final conclusion omitted by the Controller.",
  hallusinasjonarTekst: "The Controller identified hallucinations in the engineers' short-form conclusion. See the Results field and full calculation below for correct values.",
  kortSvar: "Short answer",
  resultat: "Results",
  visMellomledd: "Show {n} intermediate values",
  skjulMellomledd: "Hide intermediate values",
  foresetnaderBrukt: "Assumptions used",
  stegvisUtrekning: "Step-by-step calculation",
  stegvisBerreFormel: "Formulas only",
  stegvisAlleSteg: "All steps",
  stegvisGaaTilSteg: "Go to step",
  kvaErIkkjeRekna: "What is not calculated",
  atvaringar: "Warnings",
  konstruktorA: "Engineer A",
  konstruktorB: "Engineer B",
  konstruktorAKonfidens: "Engineer A confidence",
  konstruktorBKonfidens: "Engineer B confidence",
  konstruktorKonfidens: "Engineer confidence",
  konstruktorKonfidensPopover: "The engineer's self-reported confidence in its own answer. This is not the same as the trust score.",
  verdiktMatch: "Engineer A and Engineer B fully agree on all design values.",
  verdiktMinor: "Engineer A and Engineer B have minor differences — no critical discrepancies.",
  verdiktSignificant: "Engineer A and Engineer B have significant discrepancies in design values.",
  verdiktCritical: "Engineer A and Engineer B do not agree — manual review is required.",
  fagligMerknad: "Engineering note",
  fagligGruppeMetode: "Method",
  fagligGruppeAntakelser: "Assumptions & warnings",
  lesHeileVurderinga: "Read the full Controller assessment",
  skjulVurderinga: "Hide assessment",
  krevFagligGjennomgang: "Requires professional review",
  sjølvkontrollEtikett: "Self-check",
  sjølvkontrollIngen: "No inconsistencies found",
  sjølvkontrollFunne: "{n} inconsistency/inconsistencies found",
  sjølvkontrollSkjul: "Hide details",
  visningProfil: "View",
  profilTrygg: "Safe",
  profilStandard: "Standard",
  profilKrevGjennomgang: "Requires review",
  profilForklaringTrygg: "Agreement check passed and no warnings — this page shows the short main answer.",
  profilForklaringStandard: "Approved — details are collapsed; click to explore.",
  profilForklaringStandardMedAdvarsler: "Approved with warnings — details are collapsed; click to explore.",
  profilForklaringKrev: "Significant differences — discrepancy rows and notes are pre-expanded.",
  bUavhengigKontroll: "Engineer B — independent check",
  bEnigeMedA: "AGREES with A",
  bMindreSkilnader: "Minor differences from A",
  bVesentlegAvvik: "Significant difference from A",
  bKritiskUsemje: "Critical disagreement with A",
  bKonfidens: "confidence",
  bUtanComparison: "no comparison available",
  loysteOppgavaUtan: "Solved the task without seeing Engineer A's answer",
  konstruktorBKonklusjon: "ENGINEER B CONCLUSION",
  konstruktorBResultat: "ENGINEER B RESULTS",
  samanliknarSkilnader: "Comparator — differences found",
  numeriskeSkilnader: "Numerical differences",
  metodiskeSkilnader: "Methodological differences",
  forskjellarForesetnader: "Assumption differences",
  internInkonsistens: "Internal inconsistency",
  tabellFelt: "Field",
  tabellSkilnad: "Difference",
  tabellAlvor: "Severity",
  samanliknarKvifor: "Why:",
  samanliknarAVerdi: "Engineer A",
  samanliknarBVerdi: "Engineer B",
  generelleMerknader: "General notes from the Comparator",
  skjulMerknader: "Hide notes",
  resultatetForebels: "The result is preliminary and must be checked by a qualified professional.",
  generRapport: "Generate report →",
};

function sprint336FallbackEnglishLabel(key: string, fallback: string): string {
  return SPRINT336_ENGLISH_LABEL_BY_KEY[key] ?? sprint335PolishEnglishText(fallback);
}
function englishProductPolish(value: string): string {
  return String(value ?? "")
    .replace(/\bBEREGNINGSNOTAT\b/g, "CALCULATION NOTE")
    .replace(/\bBEREGNINGSARK\b/g, "CALCULATION SHEET")
    .replace(/\bDOKUMENT-ID\b/g, "DOCUMENT ID")
    .replace(/\bRapportør\b/g, "Reporter")
    .replace(/\bTILLIT-SKÅR\b/g, "TRUST SCORE")
    .replace(/\bVIKTIG MERKNAD\b/g, "IMPORTANT NOTE")
    .replace(/\bMIDDELS\b/g, "MEDIUM")
    .replace(/\bGOOD\b/g, "GOOD")
    .replace(/\bGod\b/g, "Good")
    .replace(/\bEnige\b/g, "Agreement")
    .replace(/\bGodkjent\b/g, "Approved")
    .replace(/\bHØY\b/g, "HIGH")
    .replace(/\bHøg\b/g, "HIGH")
    .replace(/\bLAV\b/g, "LOW")
    .replace(/\bDelvis klar\b/g, "Partly ready")
    .replace(/\bMindre avvik\b/g, "Minor differences")
    .replace(/\bMed advarsel\b/g, "With warnings")
    .replace(/\bGodkjent med advarsler\b/g, "Approved with warnings")
    .replace(/\bPRELIMINARY\b/g, "PRELIMINARY")
    .replace(/\bForeløpig\b/g, "Preliminary")
    .replace(/Beregningen er foreløpig godkjent med advarsler\. Forbeholdene må avklares før prosjekteringsbruk\./gi, "The calculation is preliminarily approved with warnings. The reservations must be resolved before use in design work.")
    .replace(/Beregningen er foreløpig godkjent med advarsler\. Skal verifiseres av ansvarlig fagperson før bruk i prosjektering\./gi, "The calculation is preliminarily approved with warnings and must be verified by a qualified professional before use in design work.")
    .replace(/Må kontrolleres av fagperson før bruk i prosjektering\./gi, "Must be checked by a qualified professional before use in design work.")
    .replace(/må kontrolleres av fagperson før bruk i prosjektering/gi, "must be checked by a qualified professional before use in design work")
    .replace(/\bEngineer A\b/g, "Engineer A")
    .replace(/\bEngineer B\b/g, "Engineer B")
    .replace(/\bEngineer\b/g, "Engineer")
    .replace(/\bComparator\b/g, "Comparator")
    .replace(/\bComparator\b/g, "Comparator")
    .replace(/\bController\b/g, "Controller")
    .replace(/\bFaglig merknad\b/gi, "Engineering note")
    .replace(/\bANTAKELSER & ADVARSLER\b/g, "ASSUMPTIONS & WARNINGS")
    .replace(/\bMETODISKE FORSKJELLER\b/g, "METHODOLOGICAL DIFFERENCES")
    .replace(/\bFORSKJELLER I FORUTSETNINGER\b/g, "ASSUMPTION DIFFERENCES")
    .replace(/\bSkjul merknader\b/g, "Hide notes")
    .replace(/\bOTHER\b/g, "OTHER");
}

function englishResultLabelOverride(label: string): string | null {
  const key = String(label ?? "").toLowerCase().replace(/[\s_.-]+/g, "").replace(/,/g, "");
  const known: Record<string, string> = {
    lptypical: "Typical Lp",
    lrtypical: "Typical Lr",
    lpapprox: "Approx. Lp",
    lrapprox: "Approx. Lr",
    lspan: "Span, L",
    span: "Span, L",
    spanl: "Span, L",
    ltbzone: "LTB zone",
    ltbregime: "LTB regime",
    ltbscreening: "LTB screening",
    phibmpupperbound: "φbMp upper bound",
    phibmn: "φbMn",
    phivvn: "φvVn",
    loadfactord: "Dead load factor",
    loadfactorl: "Live load factor",
    deadloadfactor: "Dead load factor",
    liveloadfactor: "Live load factor",
    cbassumed: "Assumed Cb",
    cbactual: "Actual Cb",
    loadcombination: "Load combination",
  };
  return known[key] ?? null;
}


export function sprint335PolishEnglishText(value: string): string {
  return sanitizeAiscGuardedOutputText(String(value ?? "")
    .replace(/\bBEREGNINGSNOTAT\b/g, "CALCULATION NOTE")
    .replace(/\bBEREKNINGSNOTAT\b/g, "CALCULATION NOTE")
    .replace(/\bBEREGNINGSARK\b/g, "CALCULATION SHEET")
    .replace(/\bBEREKNINGSARK\b/g, "CALCULATION SHEET")
    .replace(/\bDOKUMENT-ID\b/g, "DOCUMENT ID")
    .replace(/\bRapportør\b/g, "Reporter")
    .replace(/\bTILLIT-SKÅR\b/g, "TRUST SCORE")
    .replace(/\bVIKTIG MERKNAD\b/g, "IMPORTANT NOTE")
    .replace(/\bMIDDELS\b/g, "MEDIUM")
    .replace(/\bMiddels\b/g, "Medium")
    .replace(/\bHØY\b/g, "HIGH")
    .replace(/\bHøy\b/g, "High")
    .replace(/\bHøg\b/g, "High")
    .replace(/\bLAV\b/g, "LOW")
    .replace(/\bLav\b/g, "Low")
    .replace(/\bDelvis klar\b/g, "Partly ready")
    .replace(/\bMindre avvik\b/g, "Minor differences")
    .replace(/\bMed advarsel\b/g, "With warnings")
    .replace(/\bGodkjent med advarsler\b/g, "Approved with warnings")
    .replace(/\bPRELIMINARY\b/g, "PRELIMINARY")
    .replace(/\bForeløpig\b/g, "Preliminary")
    .replace(/Beregningen er foreløpig godkjent med advarsler\. Forbeholdene må avklares før prosjekteringsbruk\./gi, "The calculation is preliminarily approved with warnings. The reservations must be resolved before use in design work.")
    .replace(/Beregningen er foreløpig godkjent med advarsler\. Skal verifiseres av ansvarlig fagperson før bruk i prosjektering\./gi, "The calculation is preliminarily approved with warnings and must be verified by a qualified professional before use in design work.")
    .replace(/Det er små forskjeller mellom svarene, hovedsakelig avrunding\./gi, "There are minor differences between the answers, mainly rounding.")
    .replace(/Tabellen viser de viktigste kontrollpunktene\. Full variabel-\/pipeline-sporing finnes i nettversjonen:/gi, "The table shows the most important control points. Full variable and pipeline trace is available in the web version:")
    .replace(/Må kontrolleres av fagperson før bruk i prosjektering\./gi, "Must be checked by a qualified professional before use in design work.")
    .replace(/må kontrolleres av fagperson før bruk i prosjektering/gi, "must be checked by a qualified professional before use in design work")
    .replace(/\bEngineer A\b/g, "Engineer A")
    .replace(/\bEngineer B\b/g, "Engineer B")
    .replace(/\bEngineeren\b/g, "the engineer")
    .replace(/\bEngineer\b/g, "Engineer")
    .replace(/\bComparator\b/g, "Comparator")
    .replace(/\bComparator\b/g, "Comparator")
    .replace(/\bController\b/g, "Controller")
    .replace(/\bFaglig merknad\b/gi, "Engineering note")
    .replace(/\bANTAKELSER & ADVARSLER\b/g, "ASSUMPTIONS & WARNINGS")
    .replace(/\bMETODISKE FORSKJELLER\b/g, "METHODOLOGICAL DIFFERENCES")
    .replace(/\bFORSKJELLER I FORUTSETNINGER\b/g, "ASSUMPTION DIFFERENCES")
    .replace(/\bSkjul merknader\b/g, "Hide notes")
    .replace(/\bSkjul vurderingen\b/g, "Hide assessment")
    .replace(/\bSelvkontroll: Ingen inkonsistenser funnet\b/g, "Self-check: no inconsistencies found")
    .replace(/\bOTHER\b/g, "OTHER")
    .replace(/\bNavn · stilling · foretak\b/g, "Name · title · company")
    .replace(/\bDD\.MM\.ÅÅÅÅ\b/g, "MM/DD/YYYY")
    .replace(/\bFullstendighet\b/g, "Completeness")
    .replace(/\bHøg\b/g, "High")
    .replace(/\bLåg\b/g, "Low")
    .replace(/\båtvar\w*\b/gi, "warn")
    .replace(/\bprosjektering\b/gi, "design work")
    .replace(/\bfagperson\b/gi, "qualified professional"));
}

export function sprint335EnglishResultLabel(label: string): string | null {
  const key = String(label ?? "").toLowerCase().replace(/[\s_.-]+/g, "").replace(/,/g, "");
  const known: Record<string, string> = {
    d: "Dead load, D",
    deadloadd: "Dead load, D",
    l: "Live load, L",
    liveloadl: "Live load, L",
    lptypical: "Typical Lp",
    lrtypical: "Typical Lr",
    lpapprox: "Approx. Lp",
    lrapprox: "Approx. Lr",
    lspan: "Span, L",
    span: "Span, L",
    spanl: "Span, L",
    ltbflag: "LTB flag",
    ltbzone: "LTB zone",
    ltbregime: "LTB regime",
    ltbscreening: "LTB screening",
    phibmpupperbound: "φbMp upper bound",
    phibmn: "φbMn",
    phivvn: "φvVn",
    loadfactord: "Dead load factor",
    gamma_d: "Dead load factor",
    gammad: "Dead load factor",
    γd: "Dead load factor",
    loadfactorl: "Live load factor",
    gamma_l: "Live load factor",
    gammal: "Live load factor",
    γl: "Live load factor",
    deadloadfactor: "Dead load factor",
    liveloadfactor: "Live load factor",
    cbassumed: "Assumed Cb",
    cbactual: "Actual Cb",
    loadcombination: "Load combination",
    loadchar: "Characteristic load",
    factorl: "Live load factor",
    factord: "Dead load factor",
    vu: "Vu",
    mu: "Mu",
    wu: "wu",
  };
  return known[key] ?? null;
}


function sanitizeAiscGuardedOutputTextBase(value: string): string {
  return String(value ?? "")
    .replace(/Cb\s*=\s*1\.0\s+is\s+a\s+conservative\s+screening\s+assumption\s+only\.\s*The actual Cb for uniform load on a simply supported beam is 1\.14;?\s*using Cb\s*=\s*1\.0[^.]*\./gi, "Cb = 1.0 is used only as a conservative screening assumption. No refined Cb value is computed or assumed without verified input.")
    .replace(/The actual Cb for (?:a )?uniform(?:ly)? load(?:ed)? on a simply supported beam is 1\.14[^.]*\./gi, "No refined Cb value is computed or assumed without verified input.")
    .replace(/actual Cb[^.]{0,120}(?:1\.14|Cb\s*>\s*1\.0)[^.]*\./gi, "No refined Cb value is computed or assumed without verified input.")
    .replace(/Cb\s*(?:≈|=|is approximately)\s*1\.14/gi, "refined Cb value is not computed or assumed")
    .replace(/Cb\s*>\s*1\.0/gi, "refined Cb value not determined")
    .replace(/W12x26\s+nominally\s+26\s*lb\/ft\s*=\s*0\.026\s*kip\/ft/gi, "beam self-weight from verified input")
    .replace(/If the designer intends to include self-weight\s*\(beam self-weight from verified input\),\s*wu and resulting Mu and Vu should be recalculated\./gi, "If the designer intends to include beam self-weight, it must be supplied as verified input or calculated from an approved data source before recalculating demand.")
    .replace(/If the designer intends to include self-weight[^.]{0,180}26\s*lb\/ft[^.]*\./gi, "If the designer intends to include beam self-weight, it must be supplied as verified input or calculated from an approved data source before recalculating demand.")
    .replace(/The W12x26 is a relatively shallow,\s*wide-flange section\.\s*A 20 ft unbraced length represents a large fraction of the section's lateral stiffness capacity\./gi, "No AISC shape geometry or stiffness conclusion is assumed. LTB may be critical because Lb equals the full span and no intermediate lateral bracing is provided.")
    .replace(/relatively shallow,\s*wide-flange section/gi, "section with unverified AISC properties")
    .replace(/\bshallow W-shape\b/gi, "section with unverified AISC properties")
    .replace(/\bnarrow-flanged\b/gi, "section with unverified AISC properties")
    .replace(/;\s*(?:phi_b|phib)\*Mn reduction below (?:phi_b|phib)\*Mp expected; verified section properties required/gi, "; verified AISC section properties and Chapter F checks are required")
    .replace(/(?:phi_b|phib)\*Mn reduction below (?:phi_b|phib)\*Mp expected/gi, "AISC flexural strength cannot be determined without verified section properties")
    .replace(/The available flexural strength (?:phi_b|phib)\*Mn is likely to be reduced below the plastic moment (?:phi_b|phib)\*Mp due to lateral-torsional buckling\./gi, "Available flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks.")
    .replace(/available flexural strength[^.]{0,140}likely[^.]{0,120}reduced below[^.]*\./gi, "Available flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks.")
    .replace(/represents a significant LTB exposure/gi, "requires an LTB check with verified AISC data")
    .replace(/Adding bracing at midspan or third-points would substantially increase (?:phi_b|phib)\*Mn and is recommended if the section is found to be inadequate\./gi, "Adding verified lateral bracing may improve LTB performance, but the effect must be checked using verified AISC Manual properties and Chapter F procedures.")
    .replace(/would substantially increase (?:phi_b|phib)\*Mn/gi, "may improve LTB performance after verified AISC checking")
    .replace(/using Cb\s*=\s*1\.0 understates available capacity in a full design calculation/gi, "no refined Cb effect is claimed without verified input")
    .replace(/Both engineers treat this correctly as a screening conservatism rather than a computed value\./gi, "Any refined Cb effect must be computed from verified input before being used.")
    .replace(/Both engineers respect the AISC Data Guard and withhold all tabulated section properties/gi, "The AISC Data Guard requires tabulated section properties to be verified before capacity conclusions are made")
    .replace(/No AISC Manual tabulated values were generated or estimated — the AISC Data Guard was respected throughout by both engineers\./gi, "No AISC Manual section-property values are accepted unless supplied by verified input or an approved application data source.");
}


export function sprint3310eFix4ComparatorResidueText(value: string): string {
  return String(value ?? "")
    .replace(
      /Engineer B notes in limitations that the actual Cb[\s\S]{0,900}?Any refined Cb effect must be computed from verified input before being used\./gi,
      "No refined Cb value is computed or assumed without verified input. Any refined Cb effect must be computed from verified input before being used.",
    )
    .replace(
      /No refined Cb value is computed or assumed without verified input\.0\s+does not establish any refined\s+Cb effect without verified input\./gi,
      "No refined Cb value is computed or assumed without verified input. Any refined Cb effect must be computed from verified input before being used.",
    )
    .replace(
      /verified input\.0\s+does not establish any refined\s+Cb effect without verified input\./gi,
      "verified input. Any refined Cb effect must be computed from verified input before being used.",
    )
    .replace(
      /A verified AISC Manual section properties and Chapter F checks is required/gi,
      "Verified AISC Manual section properties and Chapter F checks are required",
    )
    .replace(
      /a verified AISC Manual section properties and Chapter F checks for the W12x26 is required/gi,
      "verified AISC Manual section properties and Chapter F checks for the W12x26 are required",
    )
    .replace(
      /a verified AISC Manual section properties and Chapter F checks is required/gi,
      "verified AISC Manual section properties and Chapter F checks are required",
    )
    .replace(
      /LTB may be critical and requires verified AISC Chapter F checking\. A verified AISC Manual section properties and Chapter F checks is required/gi,
      "LTB may be critical and requires verified AISC Manual section properties and Chapter F checks",
    );
}


export function sprint3310fReportPolishText(value: string): string {
  return String(value ?? "")
    .replace(
      /Engineer B notes in limitations that the actual Cb[^.\n]*(?:\.[\s\S]{0,500}?before being used\.)?/gi,
      "No refined Cb value is computed or assumed without verified input. Any refined Cb effect must be computed from verified input before being used.",
    )
    .replace(
      /Engineer A makes the same point in the limitations section,\s*citing refined Cb value is not computed or assumed for a uniformly loaded simply supported beam\./gi,
      "Engineer A also treats any refined Cb effect as requiring verified input.",
    )
    .replace(
      /No refined Cb value is computed or assumed without verified input\.\s*Any refined Cb effect must be computed from verified input before being used\.\s*No refined Cb value is computed or assumed without verified input\.\s*Any refined Cb effect must be computed from verified input before being used\./gi,
      "No refined Cb value is computed or assumed without verified input. Any refined Cb effect must be computed from verified input before being used.",
    )
    .replace(
      /LTB may be critical and requires verified AISC Chapter F checking\.\s*Verified AISC Manual section properties and Chapter F checks are required/gi,
      "LTB may be critical; verified AISC Manual section properties and Chapter F checks are required",
    )
    .replace(
      /Verified AISC Manual section properties and Chapter F checks for the W12x26 are required before any capacity or adequacy conclusion can be drawn\./gi,
      "Verified AISC Manual section properties and Chapter F checks are required before any capacity or adequacy conclusion can be drawn.",
    )
    .replace(
      /Verified AISC Manual section properties and Chapter F checks are required before the W12x26 can be accepted for this span and loading\./gi,
      "Verified AISC Manual section properties and Chapter F checks are required before the section can be accepted for this span and loading.",
    );
}


export function sprint3310fFixDuplicateCbPolishText(value: string): string {
  const refined =
    "No refined Cb value is computed or assumed without verified input. Any refined Cb effect must be computed from verified input before being used.";

  return String(value ?? "")
    .replace(/;\s*Verified AISC Manual/g, "; verified AISC Manual")
    .replace(/;\s*Verified AISC section/g, "; verified AISC section")
    .replace(
      /No refined Cb value is computed or assumed without verified input\.\s*Any refined Cb effect must be computed from verified input before being used\.\s*No refined Cb value is computed or assumed without verified input\.\s*Any refined Cb effect must be computed from verified input before being used\./gi,
      refined,
    )
    .replace(
      /No refined Cb value is computed or assumed without verified input\.\s*Any refined Cb effect must be computed from verified input before being used\.\s*Engineer A also treats any refined Cb effect as requiring verified input\.\s*Any refined Cb effect must be computed from verified input before being used\./gi,
      refined,
    )
    .replace(
      /No refined Cb value is computed or assumed without verified input\.\s*Any refined Cb effect must be computed from verified input before being used\.\s*Engineer A also treats any refined Cb effect as requiring verified input\./gi,
      refined,
    )
    .replace(
      /Any refined Cb effect must be computed from verified input before being used\.\s*Any refined Cb effect must be computed from verified input before being used\./gi,
      "Any refined Cb effect must be computed from verified input before being used.",
    )
    .replace(
      /No refined Cb value is computed or assumed without verified input\.\s*No refined Cb value is computed or assumed without verified input\./gi,
      "No refined Cb value is computed or assumed without verified input.",
    );
}


export function sprint3310gFixAiscVariantCoverageText(value: string): string {
  return String(value ?? "")
    // Middle-dot / unicode phi variants of the forbidden flexural-strength claim.
    .replace(
      /\b(?:phi_b|phib|φb)\s*[·*]?\s*Mn\s+expected\s+to\s+be\s+reduced\s+below\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp\b/gi,
      "verified AISC Manual section properties and Chapter F checks are required",
    )
    .replace(
      /\b(?:phi_b|phib|φb)\s*[·*]?\s*Mn\s+is\s+expected\s+to\s+be\s+meaningfully\s+reduced\s+below\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp\b/gi,
      "AISC flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks",
    )
    .replace(
      /available flexural strength\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mn[^.]{0,180}(?:expected|may be|likely)[^.]{0,120}(?:reduced below|less than|below)\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp[^.]*\./gi,
      "Available flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    )
    .replace(
      /With Lb\s*=\s*20\s*ft[^.]{0,180}available flexural strength\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mn[^.]{0,180}(?:less than|below)\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp[^.]*\./gi,
      "With Lb equal to the full span and no intermediate lateral bracing, LTB may be critical; verified AISC Manual section properties and Chapter F checks are required.",
    )

    // Shape-memory claims that must not appear without verified AISC Manual data.
    .replace(
      /-\s*W12x26\s+is\s+a\s+relatively\s+compact,\s*light\s+W-shape\s*/gi,
      "- No AISC shape compactness, geometry, weight, or stiffness conclusion is assumed without verified data. ",
    )
    .replace(
      /\bW12x26\s+is\s+a\s+relatively\s+compact,\s*light\s+W-shape\b/gi,
      "No AISC shape compactness, geometry, weight, or stiffness conclusion is assumed",
    )
    .replace(
      /\bThe W12x26\s+is\s+a\s+light\s+section\s+for\s+a\s+20\s*ft\s+span[^.]*\./gi,
      "No AISC shape weight or adequacy conclusion is assumed without verified Manual properties.",
    )
    .replace(
      /\blight\s+section\s+for\s+a\s+20\s*ft\s+span[^.]*\./gi,
      "section adequacy cannot be judged without verified AISC Manual properties.",
    )
    .replace(
      /-\s*Lb\s*=\s*20\s*ft\s+is\s+a\s+substantial\s+unbraced\s+length\s+for\s+a\s+W12\s+section\s*/gi,
      "- Lb equals the full span with no intermediate bracing, so LTB may be critical and requires verified AISC Chapter F checking. ",
    )
    .replace(
      /\ban unbraced length equal to the full\s+20\s*ft\s+span\s+is\s+large\s+relative\s+to\s+the\s+W12\s+family\b/gi,
      "Lb equals the full span with no intermediate bracing",
    )
    .replace(
      /\blarge\s+relative\s+to\s+the\s+W12\s+family\b/gi,
      "a qualitative LTB concern requiring verified AISC data",
    )

    // Self-weight leakage variants.
    .replace(
      /Self-weight\s+of\s+the\s+W12x26\s+section\s+\(~?26\s*lb\/ft\s*=\s*0\.026\s*kip\/ft\)\s+has\s+not\s+been\s+included\s+in\s+the\s+dead\s+load\.[^.]*\./gi,
      "Beam self-weight has not been included in the dead load. If self-weight is required, it must be supplied as verified input or calculated from an approved data source before recalculating demand.",
    )
    .replace(
      /W12x26\s+section\s+\(~?26\s*lb\/ft\s*=\s*0\.026\s*kip\/ft\)/gi,
      "beam self-weight from a verified source",
    )
    .replace(
      /~?26\s*lb\/ft\s*=\s*0\.026\s*kip\/ft/gi,
      "verified beam self-weight",
    )

    // Refined Cb leakage variants.
    .replace(
      /A\s+refined\s+Cb\s+for\s+a\s+uniformly\s+loaded\s+simply\s+supported\s+beam[^.]{0,220}(?:would\s+equal|equals|is)\s+1\.14[^.]*\./gi,
      "No refined Cb value is computed or assumed without verified input.",
    )
    .replace(
      /refined\s+Cb[^.]{0,180}(?:would\s+equal|equals|is)\s+1\.14[^.]*\./gi,
      "No refined Cb value is computed or assumed without verified input.",
    )
    .replace(
      /AISC\s+quarter-point\s+formula/gi,
      "verified AISC procedure",
    )
    .replace(
      /quarter-point\s+formula/gi,
      "verified AISC procedure",
    )

    // LTB governing wording that overstates without verified Chapter F checks.
    .replace(
      /Lateral-torsional buckling \(LTB\) governs when the unbraced length Lb exceeds the plastic limit Lp\./gi,
      "Lateral-torsional buckling (LTB) evaluation requires verified AISC Chapter F limits such as Lp and Lr.",
    )
    .replace(
      /LTB\s+is\s+qualitatively\s+assessed\s+as\s+likely\s+critical[^.]*\.\s*With Lb[^.]{0,250}(?:phi_b|phib|φb)\s*[·*]?\s*Mn[^.]{0,250}(?:phi_b|phib|φb)\s*[·*]?\s*Mp[^.]*\./gi,
      "LTB may be critical because Lb equals the full span and no intermediate lateral bracing is provided. Verified AISC Manual section properties and Chapter F checks are required.",
    )
    .replace(
      /Intermediate lateral bracing is strongly recommended to improve efficiency\./gi,
      "Adding verified lateral bracing may improve LTB performance, but the effect must be checked using verified AISC Manual properties and Chapter F procedures.",
    )

    // Compact result-row wording.
    .replace(
      /LTB\s+likely\s+critical\s+—\s+Lb\s+equals\s+full\s+span;\s*verified AISC Manual section properties and Chapter F checks are required;\s*numerical classification blocked pending verified Lp,\s*Lr,\s*and section properties/gi,
      "LTB may be critical — Lb equals full span with no intermediate bracing; verified AISC Manual section properties and Chapter F checks are required",
    )
    .replace(
      /LTB\s+likely\s+critical\s+—\s+Lb\s+equals\s+full\s+span;\s*verified AISC Manual section properties and Chapter F checks are required/gi,
      "LTB may be critical — Lb equals full span with no intermediate bracing; verified AISC Manual section properties and Chapter F checks are required",
    );
}


export function sprint3310gFix2AiscFinalVariantText(value: string): string {
  return String(value ?? "")
    // Remove remaining shape adequacy / weight-strength inference.
    .replace(
      /The Controller specifically noted that the W12x26 is a light section relative to the demand of Mu\s*=\s*91\.00 kip-ft over a 20\s*ft unbraced span,\s*and the risk of inadequacy is real\./gi,
      "The Controller noted that section adequacy cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    )
    .replace(
      /\bW12x26 is a light section relative to the demand[^.]*\./gi,
      "Section adequacy cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    )
    .replace(
      /\bThe W12x26 is a light section for a 20\s*ft span[^.]*\./gi,
      "Section adequacy cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    )

    // Final flexural-reduction variants with middle dot / underscore / no underscore.
    .replace(
      /\b(?:phi_b|phib|φb)\s*[·*]?\s*Mn\s+expected\s+to\s+be\s+reduced\s+below\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp\b/gi,
      "verified AISC Manual section properties and Chapter F checks are required",
    )
    .replace(
      /\b(?:phi_b|phib|φb)\s*[·*]?\s*Mn\s+is\s+expected\s+to\s+be\s+(?:meaningfully\s+)?reduced\s+below\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp\b/gi,
      "AISC flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks",
    )
    .replace(
      /\bavailable flexural strength\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mn\s+for\s+W12x26\s+may\s+be\s+significantly\s+less\s+than\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp\b/gi,
      "available flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks",
    )
    .replace(
      /\bavailable flexural strength[^.]{0,220}(?:significantly less than|meaningfully reduced below|reduced below|less than)\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp[^.]*\./gi,
      "Available flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    )

    // Comparator table / reason variants.
    .replace(
      /LTB likely critical\s+—\s+Lb equals full span;\s*(?:phi_b|phib|φb)\s*[·*]?\s*Mn expected to be reduced below\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp;\s*numerical classification blocked pending verified Lp,\s*Lr,\s*and section properties/gi,
      "LTB may be critical — Lb equals full span with no intermediate bracing; verified AISC Manual section properties and Chapter F checks are required",
    )
    .replace(
      /Engineer A adds a more explicit statement that\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mn is expected to be reduced below\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp,\s*while Engineer B's language is slightly more cautious[^.]*\./gi,
      "Engineer A and Engineer B both indicate that LTB requires verified AISC Manual section properties and Chapter F checks before any capacity conclusion.",
    )
    .replace(
      /Engineer A:\s*LTB likely critical\s+—\s+Lb equals full span;\s*(?:phi_b|phib|φb)\s*[·*]?\s*Mn expected to be reduced below\s+(?:phi_b|phib|φb)\s*[·*]?\s*Mp;\s*numerical classification blocked pending verified Lp,\s*Lr,\s*and section properties/gi,
      "Engineer A: LTB may be critical — Lb equals full span with no intermediate bracing; verified AISC Manual section properties and Chapter F checks are required",
    )

    // Clean awkward sanitizer artifacts.
    .replace(
      /The available flexural strength AISC flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks\./gi,
      "Available flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    )
    .replace(
      /the Available flexural strength cannot be determined/gi,
      "available flexural strength cannot be determined",
    )
    .replace(
      /Qualitative assessment:\s*LTB is likely critical for this configuration\./gi,
      "Qualitative assessment: LTB may be critical for this configuration.",
    )
    .replace(
      /\bLTB is likely critical for this configuration\b/gi,
      "LTB may be critical for this configuration",
    )
    .replace(
      /\bLTB is qualitatively assessed as likely critical\b/gi,
      "LTB may be critical",
    )
    .replace(
      /No AISC shape compactness, geometry, weight, or stiffness conclusion is assumed without verified data\.\s*-\s*Lb equals the full span/gi,
      "No AISC shape compactness, geometry, weight, or stiffness conclusion is assumed without verified data. Lb equals the full span",
    )
    .replace(
      /For this beam:\s*-\s*Lb = 20 ft \(full span, bracing only at supports\)\s*-\s*No AISC shape compactness, geometry, weight, or stiffness conclusion is assumed without verified data\./gi,
      "For this beam: Lb = 20 ft (full span, bracing only at supports). No AISC shape compactness, geometry, weight, or stiffness conclusion is assumed without verified data.",
    );
}


export function sprint3310gFix3ResultViewArtifactText(value: string): string {
  return String(value ?? "")
    .replace(
      /No AISC shape weight or adequacy conclusion is assumed without verified Manual properties\.\s*\d+(?:\.\d+)?\s*kip-ft\)\.?/gi,
      "No AISC shape weight or adequacy conclusion is assumed without verified Manual properties.",
    )
    .replace(
      /No AISC shape weight or adequacy conclusion is assumed without verified Manual properties\.00\s*kip-ft\)\.?/gi,
      "No AISC shape weight or adequacy conclusion is assumed without verified Manual properties.",
    )
    .replace(
      /No AISC shape weight or adequacy conclusion is assumed without verified Manual properties\.\s*A capacity check is essential before any design decision\./gi,
      "Section adequacy cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    );
}


export function sprint3310gFix4TeaserText(value: string): string {
  return String(value ?? "")
    .replace(
      /The W12x26 is a light section for a 20\s*ft span under the given loading(?:\s*\(Mu\s*=\s*91\.00\s*kip-ft\))?\.?/gi,
      "Section adequacy cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    )
    .replace(
      /W12x26 is a light section for a 20\s*ft span[^.]*\.?/gi,
      "Section adequacy cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    )
    .replace(
      /No AISC shape weight or adequacy conclusion is assumed without verified Manual properties\.\s*00\s*kip-ft\)\.?/gi,
      "Section adequacy cannot be determined without verified AISC Manual section properties and Chapter F checks.",
    )
    .replace(
      /refined Cb value is not computed or assumed would be a refined value/gi,
      "no refined Cb value is computed or assumed",
    );
}

export function sanitizeAiscGuardedOutputText(value: string): string {
  return sprint3310gFix4TeaserText(
    sprint3310gFix3ResultViewArtifactText(
      sprint3310gFix2AiscFinalVariantText(
        sprint3310gFixAiscVariantCoverageText(
          sprint3310fFixDuplicateCbPolishText(
            sprint3310fReportPolishText(
              sprint3310eFix4ComparatorResidueText(
                sprint3310eFix2AiscGuardExtraText(
                  sanitizeAiscGuardedOutputTextBase(value),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  );
}



export function sprint3310eFix2AiscGuardExtraText(value: string): string {
  return String(value ?? "")
    .replace(/\bFORELØPIG GODKJENT\b/gi, "PRELIMINARILY APPROVED")
    .replace(/\bFOREL├ÿPIG GODKJENT\b/gi, "PRELIMINARILY APPROVED")
    .replace(/Engineer\s+Engineer A and Engineer B fully agree om alle design values\.?/gi, "Engineer A and Engineer B fully agree on all design values.")
    .replace(/Engineer A and Engineer B fully agree om alle design values\.?/gi, "Engineer A and Engineer B fully agree on all design values.")
    .replace(/fully agree om alle design values/gi, "fully agree on all design values")
    .replace(/;\s*(?:phi_b|phib)\*Mn reduction below (?:phi_b|phib)\*Mp expected; verified section properties required/gi, "; AISC flexural strength cannot be determined without verified section properties and Chapter F checks")
    .replace(/(?:phi_b|phib)\*Mn reduction below (?:phi_b|phib)\*Mp expected;?\s*verified section properties required/gi, "AISC flexural strength cannot be determined without verified section properties and Chapter F checks")
    .replace(/(?:phi_b|phib)\*Mn reduction below (?:phi_b|phib)\*Mp expected/gi, "AISC flexural strength cannot be determined without verified section properties and Chapter F checks")
    .replace(/The actual Cb for uniform load on a simply supported beam is 1\.14;?\s*using Cb\s*=\s*1\.0[^.]*\./gi, "No refined Cb value is computed or assumed without verified input.")
    .replace(/The actual Cb for a uniformly loaded simply supported beam is 1\.14[^.]*\./gi, "No refined Cb value is computed or assumed without verified input.")
    .replace(/actual Cb[^.]{0,180}1\.14[^.]*\./gi, "No refined Cb value is computed or assumed without verified input.")
    .replace(/actual Cb[^.]{0,180}Cb\s*>\s*1\.0[^.]*\./gi, "No refined Cb value is computed or assumed without verified input.")
    .replace(/Cb\s*(?:≈|=|is approximately)\s*1\.14/gi, "refined Cb value is not computed or assumed")
    .replace(/Cb\s*>\s*1\.0/gi, "refined Cb value not determined")
    .replace(/using Cb\s*=\s*1\.0 understates available capacity in a full design calculation/gi, "no refined Cb effect is claimed without verified input")
    .replace(/\(W12x26 nominally 26\s*lb\/ft\s*=\s*0\.026\s*kip\/ft\)/gi, "(beam self-weight must be verified before use)")
    .replace(/W12x26 nominally 26\s*lb\/ft\s*=\s*0\.026\s*kip\/ft/gi, "beam self-weight must be supplied as verified input or calculated from an approved data source")
    .replace(/If the designer intends to include self-weight[^.]{0,220}wu and resulting Mu and Vu should be recalculated\./gi, "If the designer intends to include beam self-weight, it must be supplied as verified input or calculated from an approved data source before recalculating demand.")
    .replace(/The W12x26 is a relatively shallow,\s*wide-flange section\.\s*A 20 ft unbraced length represents a large fraction of the section's lateral stiffness capacity\./gi, "No AISC shape geometry or stiffness conclusion is assumed. LTB may be critical because Lb equals the full span and no intermediate lateral bracing is provided.")
    .replace(/The W12x26 is a relatively shallow,\s*wide-flange section\./gi, "No AISC shape geometry conclusion is assumed.")
    .replace(/relatively shallow,\s*wide-flange section/gi, "section with unverified AISC properties")
    .replace(/\bshallow W-shape\b/gi, "section with unverified AISC properties")
    .replace(/\bnarrow-flanged\b/gi, "section with unverified AISC properties")
    .replace(/represents a significant LTB exposure/gi, "requires an LTB check with verified AISC data")
    .replace(/The available flexural strength (?:phi_b|phib)\*Mn is likely to be reduced below the plastic moment (?:phi_b|phib)\*Mp due to lateral-torsional buckling\./gi, "Available flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks.")
    .replace(/available flexural strength[^.]{0,180}likely[^.]{0,120}reduced below[^.]*\./gi, "Available flexural strength cannot be determined without verified AISC Manual section properties and Chapter F checks.")
    .replace(/Adding bracing at midspan or third-points would substantially increase (?:phi_b|phib)\*Mn and is recommended if the section is found to be inadequate\./gi, "Adding verified lateral bracing may improve LTB performance, but the effect must be checked using verified AISC Manual properties and Chapter F procedures.")
    .replace(/Engineer B notes in limitations that the actual Cb for a uniformly loaded simply supported beam is greater than 1\.0[^.]*\.\s*Engineer A makes the same point[^.]*\.\s*Any refined Cb effect must be computed from verified input before being used\./gi, "No refined Cb value is computed or assumed without verified input. Any refined Cb effect must be computed from verified input before being used.")
    .replace(/Engineer B notes in limitations that the actual Cb[^.]*greater than 1\.0[^.]*\./gi, "No refined Cb value is computed or assumed without verified input.")
    .replace(/and that Cb\s*=\s*1\.0 therefore understates available LTB capacity/gi, "and no refined Cb effect is claimed without verified input")
    .replace(/therefore understates available LTB capacity/gi, "does not establish any refined Cb effect without verified input")
    .replace(/parabolic moment diagram, refined Cb value not determined/gi, "refined Cb value not determined")
    .replace(/would remain as a conservative but appropriate screen/gi, "must not be refined without verified input")
    .replace(/LTB is flagged as a likely governing or co-governing limit state/gi, "LTB may be critical and requires verified AISC Chapter F checking")
    .replace(/The W12x26 must not be accepted for this span without a complete (?:phi_b|phib)\*Mn calculation using verified section properties\./gi, "The W12x26 must not be accepted for this span without verified AISC Manual section properties and Chapter F checks.")
    .replace(/complete (?:phi_b|phib)\*Mn calculation using verified section properties/gi, "verified AISC Manual section properties and Chapter F checks")
    .replace(/complete (?:phi_b|phib)\*Mn evaluation using verified AISC Manual section properties/gi, "verified AISC Manual section properties and Chapter F checks")
    .replace(/must be evaluated against (?:phi_b|phib)\*Mn once verified AISC Manual section properties are provided/gi, "must be evaluated using verified AISC Manual section properties and Chapter F checks")
    .replace(/would substantially increase (?:phi_b|phib)\*Mn/gi, "may improve LTB performance after verified AISC checking");
}

export const SPRINT335_NO_UNVERIFIED_AISC_VALUES_PROMPT = [
  "AISC/ASCE DATA GUARD",
  "- Do not provide concrete AISC Manual table values such as Zx, Sx, J, Cw, rts, ho, Lp, Lr, phi_b*Mp, phi_b*Mn, or phi_v*Vn unless they are explicitly provided by the user or retrieved from an approved verified data source in the application.",
  "- If section properties are missing, state that they are required and keep the result as a demand calculation / qualitative screening only.",
  "- Do not cite table values from memory. Do not say a value is tabulated unless the value is part of verified input/context.",
  "- You may state qualitative risk, e.g. LTB may be critical when Lb is large, but do not compute final AISC capacity from unverified properties.",
  "- Do not provide numerical typical ranges for AISC Manual-derived values such as Lp/Lr/Cb unless the values are verified input or retrieved from an approved application data source.",
  "- Do not provide numerical typical ranges or qualitative numeric thresholds for AISC-derived properties. Say only that LTB may be critical when unbraced length is large and no verified properties are available.",
].join("\n");

export function isInternationalEnglishContext(context: EngineeringContext | null | undefined): boolean {
  if (!context) return false;
  if (context.languagePolicy?.uiLocale === "en") return true;
  if (context.region?.countryCode && context.region.countryCode !== "NO") return true;
  if (context.standards?.family && context.standards.family !== "eurocode_norway") return true;
  return false;
}


export function hasNorwegianDefaultDisplaySignal(text: string | null | undefined): boolean {
  const value = String(text ?? "").toLowerCase();
  if (!value.trim()) return false;

  const norwegianSignals = [
    "norsk",
    "norske",
    "nynorsk",
    "bokmål",
    "bokmal",
    "eurokode-kontekst",
    "norsk/eurokode",
    "spennvidde",
    "dimensjonerande",
    "dimensjonerende",
    "fritt opplagd",
    "fritt opplagret",
    "jamt fordelt",
    "jevnt fordelt",
    "rekn ut",
    "beregn",
    "berekne",
    "beregning",
    "berekning",
  ];

  const negativeInternationalSignals = [
    "ikkje gjer aisc",
    "ikkje gjør aisc",
    "ikke gjer aisc",
    "ikke gjør aisc",
    "ikkje bruk aisc",
    "ikke bruk aisc",
    "ikkje gjer asce",
    "ikke gjør asce",
    "ikkje gjer amerikansk",
    "ikke gjør amerikansk",
    "ikkje amerikansk",
    "ikke amerikansk",
  ];

  return (
    norwegianSignals.some((signal) => value.includes(signal)) ||
    negativeInternationalSignals.some((signal) => value.includes(signal))
  );
}

export function inferEnglishEngineeringText(text: string | null | undefined): boolean {
  const value = (text ?? "").toLowerCase();
  if (!value.trim()) return false;

  // Norwegian/default PILAR runs may mention AISC/ASCE negatively
  // ("ikkje gjer AISC..."). That must not switch the report/export language to English.
  if (hasNorwegianDefaultDisplaySignal(value)) return false;

  const internationalSignals = [
    "aisc",
    "asce",
    "aci",
    "astm",
    "lrfd",
    "united states",
    "american",
    "steel construction manual",
    "kip",
    "kip-ft",
    "ksi",
    "w12x",
    "w14x",
    "w16x",
  ];

  return internationalSignals.some((signal) => value.includes(signal));
}

export function displayLanguageForContext(
  locale: Locale,
  context?: EngineeringContext | null,
): PilarDisplayLanguage {
  return isInternationalEnglishContext(context) ? "en" : locale;
}

export function inferReportDisplayLanguage(args: {
  locale: Locale;
  context?: EngineeringContext | null;
  text?: string;
}): PilarDisplayLanguage {
  if (isInternationalEnglishContext(args.context)) return "en";
  if (inferEnglishEngineeringText(args.text)) return "en";
  return args.locale;
}

export function localized<T extends string>(
  map: Record<PilarDisplayLanguage, T>,
  language: PilarDisplayLanguage,
): T {
  return map[language] ?? map.nb;
}


export function polishNorwegianRoleText(
  value: string | null | undefined,
  language: PilarDisplayLanguage = "nb",
): string {
  const isNn = language === "nn";

  const engineerA = "Konstruktør A";
  const engineerB = "Konstruktør B";
  const engineers = isNn ? "konstruktørane" : "konstruktørene";
  const bothEngineers = isNn ? "Begge konstruktørane" : "Begge konstruktørene";
  const comparator = isNn ? "Samanliknar" : "Sammenligner";
  const comparatorDef = isNn ? "Samanliknaren" : "Sammenligneren";
  const controller = "Kontrollør";
  const controllerDef = "Kontrolløren";
  const controllerGen = isNn ? "Kontrolløren si" : "Kontrollørens";
  const qualified = "kvalifisert fagperson";
  const approved = isNn ? "FØREBELS GODKJENT" : "FORELØPIG GODKJENT";
  const high = isNn ? "HØG" : "HØY";

  return sanitizeAiscGuardedOutputText(String(value ?? "")
    .replace(/\bThe calculation is approved for display as a preliminary result\.\s*Manual verification by a qualified professional is required before use in design work\./gi,
      isNn
        ? "Berekninga er godkjend for visning som førebels resultat. Manuell kontroll av kvalifisert fagperson er nødvendig før bruk i prosjektering."
        : "Beregningen er godkjent for visning som foreløpig resultat. Manuell kontroll av kvalifisert fagperson er nødvendig før bruk i prosjektering.")
    .replace(/\bThe calculation is preliminarily approved\.\s*The result must be checked by a qualified professional before use\./gi,
      isNn
        ? "Berekninga er førebels godkjend. Resultatet må kontrollerast av kvalifisert fagperson før bruk."
        : "Beregningen er foreløpig godkjent. Resultatet må kontrolleres av kvalifisert fagperson før bruk.")
    .replace(/\bPreliminary calculation\s*[—–-]\s*must be checked by a qualified professional before use in design work\.?/gi,
      isNn
        ? "Førebels berekning — må kontrollerast av kvalifisert fagperson før bruk i prosjektering."
        : "Foreløpig beregning — må kontrolleres av kvalifisert fagperson før bruk i prosjektering.")
    .replace(/\bThe result is preliminary and must be checked by a qualified professional\.?/gi,
      isNn
        ? "Resultatet er førebels og må kontrollerast av kvalifisert fagperson."
        : "Resultatet er foreløpig og må kontrolleres av kvalifisert fagperson.")
    .replace(/\bManual verification by a qualified professional is required before use in design work\.?/gi,
      isNn
        ? "Manuell kontroll av kvalifisert fagperson er nødvendig før bruk i prosjektering."
        : "Manuell kontroll av kvalifisert fagperson er nødvendig før bruk i prosjektering.")
    .replace(/\bqualified professional\b/gi, qualified)
    .replace(/\blicensed structural engineer\b/gi, qualified)
    .replace(/\bdesign work\b/gi, "prosjektering")

    .replace(/\bEngineer A and Engineer B\b/g, `${engineerA} og ${engineerB}`)
    .replace(/\bEngineer A og Engineer B\b/g, `${engineerA} og ${engineerB}`)
    .replace(/\bEngineer A and B\b/g, `${engineerA} og ${engineerB}`)
    .replace(/\bBoth engineers are\b/gi, `${bothEngineers} er`)
    .replace(/\bBoth engineers er\b/gi, `${bothEngineers} er`)
    .replace(/\bBoth engineers\b/gi, bothEngineers)
    .replace(/\btwo AI engineers\b/gi, isNn ? "to AI-konstruktørar" : "to AI-konstruktører")
    .replace(/\bAI engineers\b/gi, isNn ? "AI-konstruktørar" : "AI-konstruktører")
    .replace(/\bEngineer A\b/g, engineerA)
    .replace(/\bEngineer B\b/g, engineerB)
    .replace(/\bengineers\b/gi, engineers)
    .replace(/\bEngineer\b/g, "Konstruktør")

    .replace(/\bControllerens\b/g, controllerGen)
    .replace(/\bControlleren\b/g, controllerDef)
    .replace(/\bController\b/g, controller)
    .replace(/\bComparatoren\b/g, comparatorDef)
    .replace(/\bComparator\b/g, comparator)

    .replace(/\bBOTH ENGINEERS AGREE\b/g, isNn ? "BEGGE KONSTRUKTØRAR ER EINIGE" : "BEGGE KONSTRUKTØRER ER ENIGE")
    .replace(/\bBOTH ENGINEERS ER ENIGE\b/g, isNn ? "BEGGE KONSTRUKTØRAR ER EINIGE" : "BEGGE KONSTRUKTØRER ER ENIGE")
    .replace(/\bPRELIMINARILY APPROVED\b/g, approved)
    .replace(/\bApproved with warnings\b/g, isNn ? "Godkjent med åtvaringar" : "Godkjent med advarsler")
    .replace(/\bLOW\b/g, "LAV")
    .replace(/\bHIGH\b/g, high)
    .replace(/\bMEDIUM\b/g, "MIDDELS")
    .replace(/\bGOOD\b/g, isNn ? "GOD" : "GOD")

    .replace(/\bENGINEER B SIN KONKLUSJON\b/g, "KONSTRUKTØR B SIN KONKLUSJON")
    .replace(/\bENGINEER B SINE RESULTATER\b/g, isNn ? "KONSTRUKTØR B SINE RESULTAT" : "KONSTRUKTØR B SINE RESULTATER")
    .replace(/\bENGINEER B SINE RESULTAT\b/g, "KONSTRUKTØR B SINE RESULTAT")
    .replace(/\bFORSKJELLER I ASSUMPTIONER\b/g, isNn ? "SKILNADER I FØRESETNADER" : "FORSKJELLER I FORUTSETNINGER")
    .replace(/\bassumptioner\b/gi, isNn ? "føresetnader" : "forutsetninger")
    .replace(/\bassumptions\b/gi, isNn ? "føresetnader" : "forutsetninger")
  );
}

export function localizeGeneratedEngineeringText(
  value: string,
  language: PilarDisplayLanguage,
): string {
  if (language !== "en") return polishNorwegianRoleText(value, language);
  value = sprint335PolishEnglishText(value);
  value = englishProductPolish(value);
  return sanitizeAiscGuardedOutputText(polishEnglishGeneratedText(value)
    .replace(/\bEngineer A\b/g, "Engineer A")
    .replace(/\bEngineer B\b/g, "Engineer B")
    .replace(/\bEngineerane\b/g, "the engineers")
    .replace(/\bEngineerene\b/g, "the engineers")
    .replace(/\bControllerens\b/g, "Controller's")
    .replace(/\bControlleren\b/g, "the Controller")
    .replace(/\bController\b/g, "Controller")
    .replace(/\bComparator\b/g, "Comparator")
    .replace(/\bComparator\b/g, "Comparator")
    .replace(/\bFagperson\b/g, "Professional reviewer")
    .replace(/\bforeløpig godkjent\b/gi, "preliminarily approved")
    .replace(/\bførebels godkjend\b/gi, "preliminarily approved")
    .replace(/\bprosjektering\b/gi, "design work"));
}

export function localizeResultLabel(
  label: string,
  language: PilarDisplayLanguage,
): string {
  if (language !== "en") return label;
  const sprint335Override = sprint335EnglishResultLabel(label);
  if (sprint335Override) return sprint335Override;
  const override = englishResultLabelOverride(label);
  if (override) return override;

  const compact = label.toLowerCase().replace(/[\s_,.-]+/g, "");
  const sprint337Known: Record<string, string> = {
    ltbrisk: "LTB risk",
    ltbriskflag: "LTB risk",
    ltb: "LTB risk",
    mu: "Mu",
    vu: "Vu",
    wu: "wu",
    wd: "Dead load, D",
    wl: "Live load, L",
    d: "Dead load, D",
    lload: "Live load, L",
    load: "Load",
    loadd: "Dead load factor",
    loadl: "Live load factor",
    loadfactor: "Load factor",
    gamma: "Load factor",
    γ: "Load factor",
    gamma1: "Load factor",
    gamma12: "Dead load factor",
    gamma16: "Live load factor",
    factor_d: "Dead load factor",
    factor_l: "Live load factor",
    phibmn: "φbMn",
    phivvn: "φvVn",
    phibmnlb: "φbMn(Lb)",
  };
  if (sprint337Known[compact]) return sprint337Known[compact];
  const known: Record<string, string> = {
    lspanft: "Span, L",
    lloadchar: "Live load, L",
    dchar: "Dead load, D",
    dcr: "Demand-to-capacity ratio",
    phibmpupperbound: "φbMp upper bound",
    ltbregime: "LTB regime",
    lspan: "Span, L",
    utilization: "Utilization",
    demandcapacityratio: "Demand-to-capacity ratio",
    phivvn: "φvVn",
    phibmn: "φbMn",
    loadcombination: "Load combination",
    loadcombo: "Load combination",
    lrapprox: "Approx. Lr",
    lpapprox: "Approx. Lp",
    ltbzone: "LTB zone",
    lload: "Live load, L",
    liveload: "Live load, L",
    deadload: "Dead load, D",
    dload: "Dead load, D",
    spanl: "Span, L",
    l: "Span, L",
    lb: "Unbraced length, Lb",
    unbracedlengthlb: "Unbraced length, Lb",
    loadfactord: "Dead load factor",
    loadfactorl: "Live load factor",
    gammad: "Dead load factor",
    gammal: "Live load factor",
    cbassumed: "Assumed Cb",
    ltbflag: "LTB flag",
    ltbscreening: "LTB screening",
    mu: "Mu",
    vu: "Vu",
    wu: "wu",
    fy: "Fy",
    section: "Section",
    steelgrade: "Steel grade",
    supportconditions: "Support conditions",
    lateralbracing: "Lateral bracing",
  };

  return known[compact] ?? label
    .replace(/load\s*factor\s*d/i, "Dead load factor")
    .replace(/load\s*factor\s*l/i, "Live load factor")
    .replace(/LTBscreening/i, "LTB screening")
    .replace(/Lspan/i, "Span, L")
    .replace(/LTBregime/i, "LTB regime")
    .replace(/LTBzone/i, "LTB zone")
    .replace(/Lpapprox/i, "Approx. Lp")
    .replace(/Lrapprox/i, "Approx. Lr")
    .replace(/phibMpupperbound/i, "φbMp upper bound")
    .replace(/LTBzone/i, "LTB zone")
    .replace(/Lpapprox/i, "Approx. Lp")
    .replace(/Lrapprox/i, "Approx. Lr")
    .replace(/load_combo|loadcombo/i, "Load combination")
    .replace(/Cbassumed/i, "Assumed Cb")
    .replace(/Lload/i, "Live load, L")
    .replace(/spanL/i, "Span, L")
    .replace(/gamma_D|γD/g, "Dead load factor")
    .replace(/gamma_L|γL/g, "Live load factor");
}

export function standardShortLabel(context: EngineeringContext | null | undefined): string {
  const family = context?.standards?.family;
  if (family === "aisc_asce_aci") return "AISC/ASCE CONTEXT";
  if (family === "eurocode_norway") return "EUROCODE + NORWAY NA";
  if (family === "eurocode_general") return "EUROCODE CONTEXT";
  if (family === "eurocode_uk_na") return "EUROCODE + UK NA";
  if (family === "canada") return "CANADIAN CONTEXT";
  if (family === "australia") return "AUSTRALIAN CONTEXT";
  return "SELECTED STANDARD CONTEXT";
}

export const SPRINT337_ENGLISH_LABEL_BY_KEY: Record<string, string> = {
  // Workbench / phase headers
  workbenchEyebrow: "New calculation",
  workbenchTitle: "Describe the task",
  workbenchDescription: "Enter the request. PILAR reads it and shows the interpretation here — you can edit and re-interpret before starting the calculation.",
  calculatingEyebrow: "Step · calculating",
  calculatingTitle: "Two independent engineers solve the same problem",
  calculatingDescription: "Engineer A and Engineer B use independent methods. The Comparator checks agreement before the result is presented.",
  resultEyebrow: "Step 3 of 3 · Result",
  resultTitle: "Calculation note",
  resultDescription: "Preliminary result with agent control. Must be checked by a qualified professional before use.",

  // Result page labels
  kontrollorAvgjerd: "Controller — final decision",
  kontrollor: "Controller",
  kontrollorPopover1: "The Controller agent reads both engineers and the Comparator, then decides whether the result is safe enough to show. It does",
  kontrollorPopover2: "not",
  kontrollorPopover3: "replace professional review.",
  sluttkonklusjonUtelaten: "Final conclusion omitted by the Controller.",
  hallusinasjonarTekst: "The Controller identified hallucinations in the engineers' short-form conclusion. See the Results field and full calculation below for correct values.",
  kortSvar: "Short answer",
  resultat: "Results",
  visMellomledd: "Show {n} intermediate values",
  skjulMellomledd: "Hide intermediate values",
  foresetnaderBrukt: "Assumptions used",
  stegvisUtrekning: "Step-by-step calculation",
  stegvisBerreFormel: "Formulas only",
  stegvisAlleSteg: "All steps",
  stegvisGaaTilSteg: "Go to step",
  kvaErIkkjeRekna: "What is not calculated",
  atvaringar: "Warnings",
  konstruktorA: "Engineer A",
  konstruktorB: "Engineer B",
  konstruktorAKonfidens: "Engineer A confidence",
  konstruktorBKonfidens: "Engineer B confidence",
  konstruktorKonfidens: "Engineer confidence",
  konstruktorKonfidensPopover: "The engineer's self-reported confidence in its own solution. This is not the same as the Trust Score — it only measures one agent's confidence in itself.",
  konfidensHighA: "Engineer A reports HIGH confidence: the method is established, the necessary input is present, and the result is internally consistent. Self-assessment — not an independent verification.",
  konfidensHighB: "Engineer B reports HIGH confidence on its independent solution. B solved the task without seeing A's answer. HIGH means B is confident in its own method — agreement between A and B is a separate check.",
  konfidensMediumA: "Engineer A reports MEDIUM confidence: the method is correct, but one or more inputs are assumed or extrapolated. Check the assumptions before relying on the result.",
  konfidensMediumB: "Engineer B reports MEDIUM confidence: B solved the task, but at least one assumption is uncertain. See the assumptions in the Engineer B block.",
  konfidensLowA: "Engineer A reports LOW confidence: significant uncertainty in method or input. The result should not be used without manual verification.",
  konfidensLowB: "Engineer B reports LOW confidence in its own solution. B is uncertain about the method or input. Manual professional review is strongly recommended.",
  konstruktorBUavhengig: "Engineer B — independent check",
  bUavhengigKontroll: "Engineer B — independent check",
  loysteOppgavaUtan: "Solved the task without seeing Engineer A's answer",
  konstruktorBKonklusjon: "Engineer B conclusion",
  konstruktorBResultat: "Engineer B results",
  verdiktMatch: "Engineer A and Engineer B fully agree on the governing values.",
  verdiktMinor: "Engineer A and Engineer B have minor differences — no critical deviations.",
  verdiktSignificant: "Engineer A and Engineer B have significant deviations in governing values.",
  verdiktCritical: "Engineer A and Engineer B disagree — manual review is required.",
  fagligMerknad: "Engineering note",
  fagligGruppeMetode: "Method",
  fagligGruppeAntakelser: "Assumptions & warnings",
  lesHeileVurderinga: "Read the full Controller assessment",
  skjulVurderinga: "Hide assessment",
  krevFagligGjennomgang: "Requires professional review",
  sjølvkontrollEtikett: "Self-check",
  sjølvkontrollIngen: "No inconsistencies found",
  sjølvkontrollFunne: "{n} inconsistency/inconsistencies found",
  sjølvkontrollSkjul: "Hide details",
  visningProfil: "View",
  profilTrygg: "Safe",
  profilStandard: "Standard",
  profilKrevGjennomgang: "Requires review",
  profilForklaringTrygg: "Agreement check passed, no warnings — the page shows a short main answer.",
  profilForklaringStandard: "Approved — details are collapsed; click to explore.",
  profilForklaringStandardMedAdvarsler: "Approved with warnings — details are collapsed; click to explore.",
  profilForklaringKrev: "Significant deviations — difference rows and notes are expanded by default.",
  bEnigeMedA: "AGREES WITH A",
  bMindreSkilnader: "Minor differences from A",
  bVesentlegAvvik: "Significant deviation from A",
  bKritiskUsemje: "Critical disagreement with A",
  bKonfidens: "confidence",
  bUtanComparison: "no comparison available",
  samanliknarSkilnader: "Comparator — differences found",
  numeriskeSkilnader: "Numerical differences",
  metodiskeSkilnader: "Methodological differences",
  forskjellarForesetnader: "Assumption differences",
  internInkonsistens: "Internal inconsistency",
  tabellFelt: "Field",
  tabellSkilnad: "Difference",
  tabellAlvor: "Severity",
  samanliknarKvifor: "Why:",
  samanliknarAVerdi: "Engineer A",
  samanliknarBVerdi: "Engineer B",
  generelleMerknader: "General notes from the Comparator",
  skjulMerknader: "Hide notes",
  resultatetForebels: "The result is preliminary and must be checked by a qualified professional.",
  tilbake: "← Back",
  generRapport: "Generate report →",

  // Mission Control
  doneToComparator: "Done — sending result to Comparator",
  cellKonklusjon: "CONCLUSION",
  toAvToEinige: "2 of 2 methods agree",
};

export function buildLocalizedLabelProxyForLanguage<T extends Record<string, Record<Locale, string>>>(
  base: T,
  locale: Locale,
  language: PilarDisplayLanguage,
  english: Partial<Record<keyof T & string, string>>,
): T {
  if (language !== "en") return base;

  const clone: Record<string, Record<Locale, string>> = { ...base };
  for (const key of Object.keys(base)) {
    const explicit = english[key as keyof typeof english & string];
    const fallback = base[key]?.[locale] ?? base[key]?.nb ?? key;
    const value = explicit || sprint336FallbackEnglishLabel(key, fallback);
    clone[key] = { nb: value, nn: value };
  }

  return clone as T;
}

export function buildLocalizedLabelProxy<T extends Record<string, Record<Locale, string>>>(
  base: T,
  locale: Locale,
  context: EngineeringContext | null | undefined,
  english: Partial<Record<keyof T & string, string>>,
): T {
  if (!isInternationalEnglishContext(context)) return base;

  const clone: Record<string, Record<Locale, string>> = { ...base };
  for (const key of Object.keys(base)) {
    const explicit = english[key as keyof typeof english & string];
    const fallback = base[key]?.[locale] ?? base[key]?.nb ?? key;
    const value = explicit || sprint336FallbackEnglishLabel(key, fallback);
    clone[key] = { nb: value, nn: value };
  }

  return clone as T;
}


export function sprint337PolishEnglishText(value: string): string {
  return String(value ?? "")
    .replace(/GOOD/g, "GOOD")
    .replace(/God/g, "Good")
    .replace(/GOODKJENT/g, "APPROVED")
    .replace(/PRELIMINARILY APPROVED/g, "PRELIMINARILY APPROVED")
    .replace(/MINOR DIFFERENCES/g, "MINOR DIFFERENCES")
    .replace(/Mindre forskjeller/g, "Minor differences")
    .replace(/Enige/g, "Agreement")
    .replace(/Godkjent/g, "Approved")
    .replace(/The calculation is approved for display as a preliminary result. Manual verification by a qualified professional is required before use in design work./gi, "The calculation is approved for display as a preliminary result. Manual verification by a qualified professional is required before use in design work.")
    .replace(/Berekninga er godkjend for visning. Føreset manuell verifikasjon av ansvarleg fagperson før bruk i prosjektering./gi, "The calculation is approved for display as a preliminary result. Manual verification by a qualified professional is required before use in design work.")
    .replace(/STEG 3 AV 3 · RESULTAT/g, "STEP 3 OF 3 · RESULT")
    .replace(/Beregningsnotat/g, "Calculation note")
    .replace(/Berekningsnotat/g, "Calculation note")
    .replace(/Foreløpig resultat med agentkontroll. Må kontrolleres av fagperson før bruk./gi, "Preliminary result with agent control. Must be checked by a qualified professional before use.")
    .replace(/Førebels resultat med agentkontroll. Må kontrollerast av fagperson før bruk./gi, "Preliminary result with agent control. Must be checked by a qualified professional before use.")
    .replace(/Engineer A and Engineer B use the same basic method/gi, "Engineer A and Engineer B use the same basic method")
    .replace(/Engineer A and Engineer B use the same basic method/gi, "Engineer A and Engineer B use the same basic method")
    .replace(/Engineer B presenterer an alternative calculation route/gi, "Engineer B presents an alternative calculation route")
    .replace(/Engineer B rapporterer eksplisitt load factors/gi, "Engineer B explicitly reports the load factors")
    .replace(/Engineer B rapporterer phi_b_Mn og phi_v_Vn eksplisitt/gi, "Engineer B explicitly reports phi_b_Mn and phi_v_Vn")
    .replace(/Engineer B rapporterer/gi, "Engineer B reports")
    .replace(/Engineer A rapporterer/gi, "Engineer A reports")
    .replace(/Both engineers nemner/gi, "Both engineers note")
    .replace(/Both engineers nevner/gi, "Both engineers note")
    .replace(/Both engineers legg til grunn/gi, "Both engineers assume")
    .replace(/Both engineers legger til grunn/gi, "Both engineers assume")
    .replace(/The Cb assumption er identisk/gi, "The Cb assumption is identical")
    .replace(/The Cb assumption er identisk/gi, "The Cb assumption is identical")
    .replace(/Ingen metodisk forskjell er identifisert/gi, "No methodological difference is identified")
    .replace(/No difference i itself assumption/gi, "No difference in the assumption itself")
    .replace(/No difference/gi, "No difference")
    .replace(/Dette er ei forskjell i presentasjonsform, ikkje i metode/gi, "This is a presentation difference, not a method difference")
    .replace(/Dette er en forskjell i presentasjonsform, ikke i metode/gi, "This is a presentation difference, not a method difference")
    .replace(/while/gi, "while")
    .replace(/og/g, "and")
    .replace(/eigne resultatfelt/gi, "separate result fields")
    .replace(/eige results-felt/gi, "separate results field")
    .replace(/resultatfelt/gi, "result fields")
    .replace(/the main formula/gi, "the main formula")
    .replace(/calculation route/gi, "calculation route")
    .replace(/intern kryssjekk/gi, "internal cross-check")
    .replace(/load factors/gi, "the load factors")
    .replace(/self-weight/gi, "the self-weight")
    .replace(/uniformly loaded simple span/gi, "uniformly loaded simply supported span")
    .replace(/shear center/gi, "shear center")
    .replace(/centroid/gi, "the centroid")
    .replace(/topplastscenarioet/gi, "the top-flange loading scenario")
    .replace(/ekstra risikofaktor/gi, "additional risk factor")
    .replace(/assumption/gi, "assumption")
    .replace(/assumptioner/gi, "assumptions")
    .replace(/assumption/gi, "assumption")
    .replace(/antakinga/gi, "assumption")
    .replace(/forskjell/gi, "difference")
    .replace(/forskjeller/gi, "differences")
    .replace(/skilnad/gi, "difference")
    .replace(/skilnader/gi, "differences")
    .replace(/likeverdig/gi, "equivalent")
    .replace(/ulik/gi, "different")
    .replace(/ikkje/gi, "not")
    .replace(/ikke/gi, "not")
    .replace(/itself/gi, "itself")
    .replace(/KONSTRUKTØR B SIN KONKLUSJON/g, "ENGINEER B CONCLUSION")
    .replace(/KONSTRUKTØR B SINE RESULTATER/g, "ENGINEER B RESULTS")
    .replace(/KONSTRUKTØR B SINE RESULTAT/g, "ENGINEER B RESULTS")
    .replace(/Comparator — forskjeller funnet/gi, "Comparator — differences found")
    .replace(/Comparator — skilnader funne/gi, "Comparator — differences found")
    .replace(/Ferdig — leverer resultat til Comparator/g, "Done — sending result to Comparator")
    .replace(/Ferdig – Leverer resultat til Comparator/g, "Done — sending result to Comparator");
}

export function polishEnglishGeneratedText(value: string): string {
  return sanitizeAiscGuardedOutputText(sprint337PolishEnglishText(sprint335PolishEnglishText(value)));
}


export function inferCalculationEnglishDisplay(text: string | null | undefined): boolean {
  return inferEnglishEngineeringText(text);
}


export function sprint338PolishEnglishText(value: string): string {
  return sprint335PolishEnglishText(String(value ?? ""))
    .replace(/Fortsetter fra tidligere beregning\. Endringer oppretter en ny beregning — originalen forblir uendret\./g, "Continuing from a previous calculation. Changes create a new calculation — the original remains unchanged.")
    .replace(/Beregningen er godkjent for visning\. Forutsetter manuell verifikasjon av ansvarlig fagperson før bruk i prosjektering\./g, "The calculation is approved for display as a preliminary result. Manual verification by a qualified professional is required before use in design work.")
    .replace(/\bPRELIMINARILY APPROVED\b/g, "PRELIMINARILY APPROVED")
    .replace(/\bMINOR DIFFERENCES\b/g, "MINOR DIFFERENCES")
    .replace(/\bGOOD\b/g, "GOOD")
    .replace(/\bEngineer A and Engineer B\b/g, "Engineer A and Engineer B")
    .replace(/\bEngineer A\b/g, "Engineer A")
    .replace(/\bEngineer B\b/g, "Engineer B")
    .replace(/\bengineers\b/g, "engineers")
    .replace(/\bEngineer\b/g, "Engineer")
    .replace(/\bComparator\b/g, "Comparator")
    .replace(/\brapporterer\b/g, "reports")
    .replace(/\bwhile\b/g, "while")
    .replace(/\bonly\b/g, "only")
    .replace(/\bBoth engineers\b/g, "Both engineers")
    .replace(/\bThe Cb assumption\b/g, "The Cb assumption")
    .replace(/\bprosjektering\b/g, "design work")
    .replace(/\bfagperson\b/g, "qualified professional");
}


export function sprint339FinalNorwegianResidueText(value: string): string {
  return sanitizeAiscGuardedOutputText(String(value ?? "")
    .replace(/\bAPPROVED\s+MED\s+ADVARSLER\b/gi, "APPROVED WITH WARNINGS")
    .replace(/\bApproved\s+med\s+advarsler\b/gi, "Approved with warnings")
    .replace(/\bMED\s+ADVARSLER\b/gi, "WITH WARNINGS")
    .replace(/\bmed\s+advarsler\b/gi, "with warnings")
    .replace(/\bMINDRE\s+DIFFERENCES\b/gi, "MINOR DIFFERENCES")
    .replace(/\bMINOR\s+FORSKJELLER\b/gi, "MINOR DIFFERENCES")
    .replace(/\bsmå\s+differences\b/gi, "minor differences")
    .replace(/\bsm├Ñ\s+differences\b/gi, "minor differences")
    .replace(/\bEngineer\s+Engineer A and B\b/g, "Engineer A and Engineer B")
    .replace(/\bEngineer A and B\b/g, "Engineer A and Engineer B")
    .replace(/\bEngineer A and Engineer B har minor differences\s*[—–-]\s*ingen kritiske avvik\.?/gi, "Engineer A and Engineer B have minor differences — no critical deviations.")
    .replace(/\bEngineer A and Engineer B har små differences\s*[—–-]\s*ingen kritiske avvik\.?/gi, "Engineer A and Engineer B have minor differences — no critical deviations.")
    .replace(/\bEngineer A and Engineer B har sm├Ñ differences\s*[—–-]\s*ingen kritiske avvik\.?/gi, "Engineer A and Engineer B have minor differences — no critical deviations.")
    .replace(/\bhar minor differences\b/gi, "have minor differences")
    .replace(/\bhar små differences\b/gi, "have minor differences")
    .replace(/\bhar sm├Ñ differences\b/gi, "have minor differences")
    .replace(/\bingen kritiske avvik\b/gi, "no critical deviations")
    .replace(/HIGH means at B er trygg på its own method\s*[—–-]\s*at Engineer A and Engineer B er enige er en separat sjekk \(see verdict above\)\./gi, "HIGH means that Engineer B is confident in its own method — agreement between Engineer A and Engineer B is a separate check.")
    .replace(/HIGH means at B er trygg p├Ñ its own method\s*(?:ÔÇö|[—–-])\s*at Engineer A and Engineer B er enige er en separat sjekk \(see verdict above\)\./gi, "HIGH means that Engineer B is confident in its own method — agreement between Engineer A and Engineer B is a separate check.")
    .replace(/\bHIGH means at B er trygg på its own method\b/gi, "HIGH means that Engineer B is confident in its own method")
    .replace(/\bHIGH means at B er trygg p├Ñ its own method\b/gi, "HIGH means that Engineer B is confident in its own method")
    .replace(/\bEngineer A and Engineer B er enige\b/gi, "Engineer A and Engineer B agree")
    .replace(/\ber enige\b/gi, "agree")
    .replace(/\ber trygg\b/gi, "is confident")
    .replace(/\bFORELØPIG GODKJENT\b/g, "PRELIMINARILY APPROVED")
    .replace(/\bMINDRE FORSKJELLER\b/g, "MINOR DIFFERENCES")
    .replace(/\bBEGGE KONSTRUKTØRER ER ENIGE\b/g, "BOTH ENGINEERS AGREE")
    .replace(/\bØVRIG\b/g, "OTHER")
    .replace(/\bGOD\b/g, "GOOD")
    .replace(/Beregningen er godkjent for visning\. Forutsetter manuell verifikasjon av ansvarlig fagperson før bruk i prosjektering\./g, "The calculation is approved for display as a preliminary result. Manual verification by a qualified professional is required before use in design work.")
    .replace(/De kom frem til samme resultat\./g, "They reached the same result.")
    .replace(/Engineer A and B er fullstendig enige om alle dimensjonerende verdier\./g, "Engineer A and Engineer B fully agree on all design values.")
    .replace(/Engineer A og B har minor differences/g, "Engineer A and Engineer B have minor differences")
    .replace(/Engineer B reports HIGH confidence på sin uavhengige løsning\./g, "Engineer B reports HIGH confidence in its independent solution.")
    .replace(/HIGH her betyr at B er trygg på egen metode — at A and B er enige er en separat sjekk \(se verdikt over\)\./g, "HIGH means that Engineer B is confident in its own method — agreement between Engineer A and Engineer B is a separate check.")
    .replace(/Self-assessment — ikke en uavhengig verifikasjon\./g, "Self-assessment — not an independent verification.")
    .replace(/Engineer A og Engineer B/g, "Engineer A and Engineer B")
    .replace(/Engineer A og B/g, "Engineer A and Engineer B")
    .replace(/A og B/g, "Engineer A and Engineer B")
    .replace(/er fullstendig enige/g, "fully agree")
    .replace(/dimensjonerende verdier/g, "design values")
    .replace(/på sin uavhengige løsning/g, "in its independent solution")
    .replace(/HIGH her betyr/g, "HIGH means")
    .replace(/egen metode/g, "its own method")
    .replace(/se verdikt over/g, "see verdict above")
    .replace(/same grunnleggjande metode/g, "the same basic method")
    .replace(/brukar/g, "use")
    .replace(/bruker/g, "use")
    .replace(/medan/g, "while")
    .replace(/berre/g, "only")
    .replace(/hovudformelen/g, "the main formula")
    .replace(/utrekningsrute/g, "calculation route")
    .replace(/ein alternativ/g, "an alternative")
    .replace(/som ein intern kryssjekk/g, "as an internal cross-check")
    .replace(/Dette er ei forskjell i presentasjonsform, ikkje i metode\./g, "This is a presentation difference, not a methodological difference.")
    .replace(/lastfaktorane/g, "load factors")
    .replace(/som eigne resultatfelt/g, "as separate result fields")
    .replace(/tekstbeskrivinga/g, "the text description")
    .replace(/Innhaldet er likeverdig men strukturen er ulik\./g, "The content is equivalent, but the structure differs.")
    .replace(/Begge konstruktørar/g, "Both engineers")
    .replace(/Begge konstruktører/g, "Both engineers")
    .replace(/konstruktørar/g, "engineers")
    .replace(/konstruktører/g, "engineers")
    .replace(/Konstruktør A/g, "Engineer A")
    .replace(/Konstruktør B/g, "Engineer B")
    .replace(/Konstruktør/g, "Engineer")
    .replace(/Cb-antaginga/g, "The Cb assumption")
    .replace(/antaginga/g, "assumption")
    .replace(/føresetnad/g, "assumption")
    .replace(/føresetnader/g, "assumptions")
    .replace(/sjølve/g, "itself")
    .replace(/Ingen forskjell/g, "No difference")
    .replace(/ingen forskjell/g, "no difference")
    .replace(/mellomledd/g, "intermediate value"));
}
